### PR TITLE
Disable Divi caching

### PR DESCRIPTION
**Pull request by kat3samsin**
## Description

Added disabling of Divi Caching by default. VIP already supports page and object caching Divi Caching can cause bloated media directory.
[Docs](https://docs.wpvip.com/plugins/incompatibilities/#divi)

### Disables Divi plugin caching
Added disabling of Divi Caching by default. 

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [ ] This change works and has been tested on a sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation).

### CODE REVIEW

**Review by WPprodigy — COMMENTED** [review]
1) We should prevent a slew of php warnings for customer's currently defining these. So like:

```
if ( ! defined( 'ET_DISABLE_FILE_BASED_CACHE' ) ) {
	define( 'ET_DISABLE_FILE_BASED_CACHE', true );
}
```

2) Should we also be including the rest of the logic mentioned here (with additional safeguards to not register and constant that is already set): https://docs.wpvip.com/plugins/incompatibilities/#divi ?

3) Lastly, let's try to limit the scope of the code to only running when we're sure it is needed - i.e. Divi is present on the site. So wrapping all of the logic inside of something like `if defined( 'ET_CORE_VERSION' ) { ... }`. Load order will be important though, might have to hook it all onto `after_setup_theme` for example.

**Comment by kat3samsin** [comment]
Thanks for the detailed feedback @WPprodigy! I've applied changes in e7d167bf2b66adb0c6e8cc88d900dff69c8d98a0

**Comment by rinatkhaziev** [comment]
@kat3samsin thanks! 

I'm not entirely sure how Divi caching works, is it appropriate for it to use VIP filesystem at all?

**Comment by kat3samsin** [comment]
@rinatkhaziev thanks for looking.
> I'm not entirely sure how Divi caching works, is it appropriate for it to use VIP filesystem at all?

From what I understand, the dynamic loading (dynamic css) feature of Divi is trying to write in `wp_content` which is not allowed on the VIP filesystem. This PR disables the dynamic loading feature if the plugin is installed so that customers would not need to manually apply the [instructions](https://docs.wpvip.com/plugins/incompatibilities/#divi) from the docs.

**Review by rinatkhaziev — APPROVED** [review]

**Pull request merged**
