### PR TITLE
FORNO-283: Increase timeout for file deletion

### PR DESCRIPTION
**Pull request by hanifn**
## Description

Increase the timeout for file delete requests to the File Service to reduce the amount of PHP warnings occurring due to request timeout errors.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.

## Steps to Test

1. Check out PR.
1. Upload changes to a sandboxed site
1. Go to `wp-admin` > `media`
1. Ensure that media upload and delete is working as expected

### CODE REVIEW

**Review by rinatkhaziev — CHANGES_REQUESTED** [review]
5 seems to be a bit drastic for me. 

Let's start with 3 and see how that goes.

Additionally, were you able to look at it from the other side? I.e. what takes it so long on the backend.

**Comment by hanifn** [comment]
> 5 seems to be a bit drastic for me.
>
> Let's start with 3 and see how that goes.

That's probably a good idea.

> Additionally, were you able to look at it from the other side? I.e. what takes it so long on the backend.

Yeah me and @alexcriss took a look since Friday but we've got nothing so far

**Review by rinatkhaziev — APPROVED** [review]
Thanks for addressing!

**Comment by hanifn** [comment]
r1230-stacks

**Pull request merged**
