### PR TITLE
Do not sync index on fake term updates

### PR DESCRIPTION
**Pull request by sjinks**
## Description

Implementation of @rinatkhaziev's Automattic/ElasticPress#132 for mu-plugins

### Plugin Updated: VIP Search

Do not synchronize index on term updates that update nothing (e.g., when a user clicks Save without modifying anything).

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

The CI should pass — I have added unit tests for this feature.

### CODE REVIEW

**Review by rinatkhaziev — APPROVED** [review]
Awesome, thanks!

**Comment by rebeccahum** [comment]
This might be worth PRing upstream to see if it will be accepted. Out of curiosity, how come you decided to add it as a standalone? To avoid further conflicts when syncing upstream?

**Comment by sjinks** [comment]
Yes, the plan was to test it here, then submit it to 10up, and kill the code after the next sync.

The fewer derivations from upstream we have, the easier it will be to sync and resolve merge conflicts.

**Comment by sjinks** [comment]
r2120-stacks

**Pull request merged**
