### PR TITLE
Cache Manager: Purge posts page

### LINKED ISSUE #241: Purge posts page
If the site is using a different page to list posts, i.e. `page_for_posts`, we should purge that posts page URL.

### PR DESCRIPTION
**Pull request by GaryJones**
## Description

If the site is using a different page to list posts, i.e. `page_for_posts`, we should purge that posts page URL.

We limit it to when the post type is a `post`, to avoid unnecessarily clearing an index of `post` posts, when a custom post type was what was updated.

Fixes #241.

_Needs actual testing, and possibly an update to some documentation somewhere._

### Update: Cache Manager

When clearing a post URL, all clear page_for_posts if there's one present.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Outline the steps to test and verify the PR here.

[Needs completing]

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
I'm marking this as "ready to deploy" as the change is pretty low-risk and the testing didn't seem to have progressed since 2019 :)

**Review by pauarge — APPROVED** [review]
LGTM

**Comment by GaryJones** [comment]
Noting that https://docs.wpvip.com/technical-references/caching/page-cache/ needs an extra list item added to it once this has been merged.

**Comment by rinatkhaziev** [comment]
r1610-stacks

**Pull request merged**
