### PR TITLE
remove gh-pages

### PR DESCRIPTION
**Pull request by pschoffer**
## Description

As we are revisiting CI pipelines on this project we decided to drop `gh-pages` building job. We have public and internal documentation which is hosted independently, so removing this documentation instead of maintaining it seems reasonable.  

**Note**: After this gets merged we should also remove:
* ssh key - 25:57:4c:ef:c1:ff:80:ee:36:1a:a9:0b:d2:67:61:bb from both CircleCI project settings and GH project settings
* Remove Github pages config for this repository

### Deprecating GH pages 

GH pages previously hosted at http://automattic.github.io/vip-go-mu-plugins/index.html will no longer be updated and will be removed in the future. Please contact VIP support if you would have any concerns.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Review by pauarge — CHANGES_REQUESTED** [review]
I think `README-PUBLIC.md` cannot be deleted since it's the one being published in `vip-go-mu-plugins-built`

**Comment by pschoffer** [comment]
Oh right! I thought it was used for docs, not the built repo. Brought it back

**Review by pauarge — APPROVED** [review]
LGTM

**Comment by pschoffer** [comment]
No production code change

**Pull request merged**
