### PR TITLE
Allow JP Sync to run during WP CLI commands

### PR DESCRIPTION
**Pull request by nickdaugherty**
## Description

Currently JP Sync is disabled for WP CLI commands. This presents a big problem for the consistency of the data, as changes from CLI commands are not synced normally.

Previously: https://github.com/Automattic/vip-go-mu-plugins/pull/665

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. wp option update blogdescription 'My new description'
1. Check value on wpcom, not updated 😑 
1. Check out PR.
1. wp option update blogdescription 'My new description'
1. Check value on wpcom, now is updated 🎉

### CODE REVIEW

**Comment by nickdaugherty** [comment]
The only concern here is performance impacts on long-running scripts with lots of changes. JP Sync _should_ queue everything up for `shutdown`...I'm not sure if it's smart enough to queue up events for cron processing if it reaches a certain threshold of changes.

Perhaps we should enable this on non-prod sites first as a test.

**Comment by nickdaugherty** [comment]
> Seem reasonable.

Do you want to go with what we have, or roll out on a subset?

**Comment by mjangda** [comment]
I think it's fine as-is.

**Comment by nickdaugherty** [comment]
Ran out of time on this again, will try to get it shipped tomorrow.

**Pull request merged**
