### PR TITLE
Update default Jetpack version to 10.4

### PR DESCRIPTION
**Pull request by jesse-greathouse**
## Description
Update default Jetpack version to 10.4

### Plugin Updated: Jetpack 10.4

The default version of Jetpack has been updated to 10.4

## Checklist

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test
1. Check out PR.
1. Go to `wp-admin` > `Jetpack`
1. Verify the version of Jetpack is 10.4

### CODE REVIEW

**Comment by rebeccahum** [comment]
Deploy note: This PR needs to go out alongside with https://github.com/Automattic/vip-go-mu-plugins/pull/2638

**Review by rebeccahum — APPROVED** [review]

**Comment by rebeccahum** [comment]
Marking as blocked since tomorrow is the upgrade day.

**Comment by rinatkhaziev** [comment]
r2087-stacks

**Comment by rebeccahum** [comment]
v20211215.0

**Pull request merged**
