### PR TITLE
a8c-files: image_resize should return false if image does not exists

### PR DESCRIPTION
**Pull request by david-binda**
In case the `wp_get_attachment_url` returns `false`, we should return false from the `image_resize` in order to not interfere with core's `image_downsize` functionality.

See related code:
* https://developer.wordpress.org/reference/functions/wp_get_attachment_url/
* https://developer.wordpress.org/reference/functions/image_downsize/
* https://developer.wordpress.org/reference/functions/wp_get_attachment_image_url/

### CODE REVIEW

**Comment by joshbetz** [comment]
* Core checks `wp_attachment_is_image( $id )`, should we do the same?
* Returning false could change functionality because the `image_downsize()` function will now continue past the filter.

**Comment by philipjohn** [comment]
Crazy idea: What about this at line 712:

```
		// Don't try to modify a non-existent URL.
		if ( false === $img_url ) {
			add_filter( 'wp_get_attachment_image_src', function( $image ) {
				if ( true === $image ) {
					return false;
				}
			} );
			return true;
		}
```
That stops `image_downsize()` doing it's thing because [the conditional at line 201](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/media.php#L201) will evaluate to true We then catch that within `wp_get_attachment_image_src()` with [the filter](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/media.php#L851).

It feels hacky, and I'm not sure of other side effects yet.

**Comment by mjangda** [comment]
Without patch:

```
wp> wp_get_attachment_image_src( 9999, 'large' )
array(4) {
  [0] =>
  string(8) "/?w=1024"
  [1] =>
  string(4) "1024"
  [2] =>
  string(4) "1024"
  [3] =>
  bool(true)
}
```

With patch:

```
wp> wp_get_attachment_image_src( 9999, 'large' )
bool(false)
```

**Comment by mjangda** [comment]
Updated to use `wp_attachment_is_image` to match core, moved the check much earlier and just passthrough to core (which also just bails).

**Comment by mjangda** [comment]
r91676-deploy

**Pull request merged**
