### PR TITLE
Add `AllowDynamicProperties` attribute to the `WP_Object_Cache` class

### PR DESCRIPTION
**Pull request by renatonascalves**
## Description

```
 Creation of dynamic property WP_Object_Cache::$memcache_debug is deprecated
```

I found this while testing a client site on PHP 8.2 using [this project](https://github.com/alleyinteractive/mantle-framework/blob/4961ae56da6464d0b4732f075ea8e9ca2b3e2d89/src/mantle/testing/concerns/trait-wordpress-state.php#L38C21-L38C35). Oddly, this repo [uses it too](https://github.com/search?q=repo%3AAutomattic%2Fvip-go-mu-plugins%20%24wp_object_cache-%3Ememcache_debug%20&type=code).

### Added
- "Add `AllowDynamicProperties` attribute to the `WP_Object_Cache` class"

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [ ] This change works and has been tested on a sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation).

### CODE REVIEW

**Comment by renatonascalves** [comment]
For context, WP [core](https://github.com/WordPress/wordpress-develop/blob/bca94a5fe45f9414f0d11a16372895a4817b1716/src/wp-includes/class-wp-object-cache.php#L24) uses it too.

**Comment by sjinks** [comment]
This probably should go to Automattic/wp-cache-memcached

cc @rinatkhaziev @WPprodigy

**Comment by renatonascalves** [comment]
@sjinks I initially thought so too, maybe since it is not linked/tracked (via composer or submodule) to that repo, I assumed it might out of sync, or custom.

**Comment by rinatkhaziev** [comment]
@renatonascalves Thank you for your contribution! For context: we try to keep away from submodules for the mission-critical functionality due to their chaotic nature. Do you mind opening the PR against[ @automattc/wp-cache-memcached](https://github.com/Automattic/wp-cache-memcached), please?

**Comment by renatonascalves** [comment]
@rinatkhaziev https://github.com/Automattic/wp-cache-memcached/pull/7

**Comment by rinatkhaziev** [comment]
We've merged the upstream, so I'm closing this one.

**Comment by renatonascalves** [comment]
@rinatkhaziev Bumping this question: https://github.com/Automattic/wp-cache-memcached/pull/7#issuecomment-2291330753

**Pull request closed without merging**
