### PR TITLE
Update two-factor to 0.7.0

### PR DESCRIPTION
**Pull request by rinatkhaziev**
Version 0.7.0

[Release notes](https://github.com/WordPress/two-factor/releases/tag/0.7.0
)

### CODE REVIEW

**Comment by brandon-m-skinner** [comment]
Tested on Lando. TOTP works and email works.

**Comment by rinatkhaziev** [comment]
Noting that this probably needs a bit more testing, because it's such an integral part.

**Comment by mjangda** [comment]
> Noting that this probably needs a bit more testing, because it's such an integral part.

I've tested various pathways and all looks good on my end.

🚢

**Comment by rinatkhaziev** [comment]
r1161-stacks

**Pull request merged**
