### PR TITLE
Updates ElasticPress with the latest code

### PR DESCRIPTION
**Pull request by pschoffer**
## Description

This PR brings over the following PRs for the ElasticPress submodule:
https://github.com/Automattic/ElasticPress/pull/68

### Plugin Updated: VIP Search

We updated ElasticPress dependency for VIP Search to enhance the data format about the post author stored in ElasticSearch.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] (For Automatticians) I've created a changelog draft.

### CODE REVIEW

**Comment by brandon-m-skinner** [comment]
Looks okay. Just some questions:

1. How does this change existing user indexes?
2. Does this require us to re-index all user indexes we currently have?
3. Will this cause some unintended on current customers who are currently making heavy use of the user indexes(yes, there are some)?

**Comment by pschoffer** [comment]
Good questions... @brandon-m-skinner 

1) Firstly this influences Post indexable not User. It changes, what we store for the `post_author.login`. From my understanding the idea here is to be able to search posts using the user nickname as that is a common use-case.

The issue was that the user's nickname is sanitized login, where we used to store non-sanitized login. So that would match unless the login has special characters (that gets dropped in sanitization) or spaces (replaced with `-`).

2) Ideally yes, but I am not sure if that is feasible? If we wouldn't, I guess the results from ES might be inconsistent but not totally wrong + search queries may act up a bit. There is, however, `post_author.raw` that contains the same value `post_author.login` did before this change. So we could advise querying against this field if somebody still wants to query non sanitized field for some reason.

3) Apart from the things mentioned in 2) I don't see other consequences.

@rebeccahum @nickdaugherty  could you please add to/correct my answers above? Also, how do you feel about re-indexing. Could we get away with not doing it? How difficult is it to do?

**Comment by brandon-m-skinner** [comment]
Reinforcing everything is a big lift and leaving everything deliberately in an inconsistent state for a day or two might be problematic.

If it comes to this, how can these risks be mitigated?

**Comment by rebeccahum** [comment]
> There is, however, post_author.raw that contains the same value post_author.login did before this change. So we could advise querying against this field if somebody still wants to query non sanitized field for some reason.

Could we do a risk report of the current VIP Search sites to see how impactful this would be? It might end up only affecting 2-3 authors per site.

**Comment by brandon-m-skinner** [comment]
There's no easy way to query all the indexes unfortunately. Would require some questionable hackery.

Not to mention reindexing everything would 100% hit rate limiting and back up every queue. This could potentially cause widespread content discrepancies.

**Comment by rebeccahum** [comment]
Do we need to re-index everything at once or can it be throttled on a site-basis?

**Comment by nickdaugherty** [comment]
Technically we could get away without re-indexing most sites - it's only sites that are querying on user login that would notice a difference, and only for users that have a login that would be affected by sanitize_title() (which is not the norm AFAIK). 

The full content validation would be failing on any site we don't re-index, but we don't run that automatically anywhere so not a big deal.

**Comment by netsuso** [comment]
Release v1.9.0: https://github.com/Automattic/vip-go-mu-plugins/releases/tag/v1.9.0

**Pull request merged**
