### PR TITLE
Remove ‘manage’ as a mandatory JP module

### PR DESCRIPTION
**Pull request by WPprodigy**
## Description

Fixes https://github.com/Automattic/vip-go-mu-plugins/issues/1368

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. Make this change on a VIP Go site.
1. Load the backend and frontend a few times and make sure there aren't any new PHP errors.

### CODE REVIEW

**Comment by mjangda** [comment]
I assume that since this is now "baked in" to Jetpack, there's no other changes needed to support compare with Calypso/WordPress.com?

**Comment by WPprodigy** [comment]
> no other changes needed to support compare with Calypso/WordPress.com

Not sure I follow what you mean.

**Comment by mjangda** [comment]
Sorry, bad auto-correct. I meant "to support compat with Calypso/WordPress.com". As in, we can removed this but don't need any other changes to maintain existing functionality.

**Comment by WPprodigy** [comment]
Ah, yep. As far as I can tell, all the manage logic still happens. It's just not a module anymore, so removing this code should have 0 effect (aside from preventing that error).

**Comment by nickdaugherty** [comment]
@WPprodigy this hasn't been deployed, so it's getting caught up in other deploys. In the future, it's best to let members of the Platform team merge so that it can be deployed right away.

**Comment by WPprodigy** [comment]
Oh, my bad! Wasn't aware of that flow. Will do in the future :)

**Comment by mjangda** [comment]
r697-stacks

**Pull request merged**
