### PR TITLE
Adding release script

### PR DESCRIPTION
**Pull request by pauarge**
## Description

This PR adds a script for automating the release process. Instead of manually crafting the changelog, this script fetches the last PRs and automatically generates the release.

### Adding release script

Adding internal tooling for releasing mu-plugins versions.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Comment by pschoffer** [comment]
Oh this rocks!

Can we make it so it creates draft only? ... maybe, maybe this is fine though.

**Review by pschoffer — DISMISSED** [review]

**Comment by pauarge** [comment]
@pschoffer We can absolutely make it create drafts only: https://cli.github.com/manual/gh_release_create

My idea with this was to save as much steps as possible, and if we create a draft, after running the script you'd still have to go to GitHub's UI and publish the release. What do you think?

**Comment by pschoffer** [comment]
Yeah you are right! Lets go with :yolo: version:)

**Comment by pauarge** [comment]
@pschoffer In case something goes wrong with the script, these are simply Git tags that can be modified/deleted.

**Review by pschoffer — APPROVED** [review]

**Pull request merged**
