### PR TITLE
Enables search index versioning self healing

### PR DESCRIPTION
**Pull request by pschoffer**
### Search Corrupted Index Versioning self-healing

After reviewing logs from our corrupted index detection, we are confident in enabling the self-healing. This change enables the self-healing and shortens the interval between checks.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] (For Automatticians) I've created a changelog draft. 

## Steps to Test

1. Break your versioning options by running - `lando wp eval "delete_option('vip_search_index_versions');"`
1. Run `wp vip-search index-versions list post` shows correct versions (with lowest version active)
1. Add version 
1. Remove option  `lando wp eval "delete_option('vip_search_index_versions');"`
1. Run `wp vip-search index-versions list post` shows correct versions (with lowest version active)

Note:
To clean cache lock in order to test:
`lando wp eval "wp_cache_set('index_versions_self_heal_lock', 0, 'vip_search');"`

To see the current option value:
`lando wp eval "var_dump(get_option( 'vip_search_index_versions'));"`

### CODE REVIEW

**Comment by pschoffer** [comment]
Should be deployed after the storage update : https://github.com/Automattic/vip-go-mu-plugins/pull/1921

**Comment by pschoffer** [comment]
I tested this with the new storage code in and it works as expected.

**Review by brandon-m-skinner — APPROVED** [review]

**Comment by pschoffer** [comment]
r1342.

**Comment by netsuso** [comment]
Release v1.7.0
https://github.com/Automattic/vip-go-mu-plugins/releases/tag/v1.7.0

**Pull request merged**
