### PR TITLE
Updating Jetpack to 4.0.3

### PR DESCRIPTION
**Pull request by david-binda**
Updating Jetpack to 4.0.3

We are a version behind the Subversion which powers the mu-plugins in production on the VIP Go platform.

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Doh, conflicts.

**Comment by nickdaugherty** [comment]
This has been superseded by https://github.com/Automattic/vip-go-mu-plugins/pull/222, closing.

**Comment by david-binda** [comment]
Sorry for the hassle @nickdaugherty . I had prepared the PR before I noticed that you proposed to not proceed with any further merges before fix the Travis in https://github.com/Automattic/vip-go-mu-plugins/pull/220#issue-160772870

I should had closed that as it was clear it will be superseded by 4.0.4 merge :-/

**Comment by nickdaugherty** [comment]
Oh no worries.

**Pull request closed without merging**
