### PR TITLE
Clears PHPCompatibility phpcs warnings wpcom-error-handler

### PR DESCRIPTION
**Pull request by pschoffer**
## Description
Same as bellow

### Resolves PHPCompatibility phpcs warnings for PHP 7.4 - wpcom-error-handler

The warnings were already reviewed previously and deemed false positive in this case.

However, we updated the implementation here to silence/resolve the warnings.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- n/a This change has relevant unit tests (if applicable).
- n/a This change has relevant documentation additions / updates (if applicable).
- [x] (For Automatticians) I've created a changelog draft. 

## Steps to Test

* Add a fatal error to somewhere in mu-plugins e.g. -  `this_is_not_a_function();`
* Call `wp user list` see the error with `Fatal Error` prefix (added among other things by this handler)

### CODE REVIEW

**Review by netsuso — COMMENTED** [review]
I haven't found any reference to this module anywhere in mu-plugins. Probably this was left behind. Could you confirm, @nickdaugherty ?

**Comment by nickdaugherty** [comment]
@pschoffer it's still used via `register_shutdown_function()` and `set_error_handler()` in this file - it's a custom setup that handles all the logging.

**Comment by pschoffer** [comment]
@netsuso the last reply/ping from @nickdaugherty was to your comment I believe.

Any ideas to test this? The changes are mostly whitespaces and few straightforward changes but some manual test would still be nice. Maybe throwing error in some way should exercise the logic in some way?

**Comment by mjangda** [comment]
> I haven't found any reference to this module anywhere in mu-plugins

It's loaded in wp-config.php generated by VIPd and also in vip-dev-env: https://github.com/Automattic/vip-dev-env/blob/master/docker/dev-tools/wp-config-defaults.php#L27-L34

**Comment by mjangda** [comment]
> Any ideas to test this? The changes are mostly whitespaces and few straightforward changes but some manual test would still be nice. Maybe throwing error in some way should exercise the logic in some way?

Yep, yry adding a fatal error to somewhere in mu-plugins: `this_is_not_a_function();`

**Comment by pschoffer** [comment]
I have tried what Mo suggested above and did some extra debug prints to make sure everything works as before. All seems good.

**Review by brandon-m-skinner — APPROVED** [review]

**Comment by nickdaugherty** [comment]
r1318-stacks

**Pull request merged**
