### PR TITLE
e2e- Fix e2e failures related to themes update

### PR DESCRIPTION
**Pull request by bsessions85**
## Description

The default theme for WP changed and the selectors for some things we're testing changed as well.

This PR updates those selectors to get the tests passing again.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Make sure e2e tests pass in CI, with the exception of the Search test which is failing for unrelated issues

### CODE REVIEW

**Review by jesse-greathouse — APPROVED** [review]
If I understand this correctly, the values in the selectors need to change because the default template for WordPress changed.

I suppose the next logical question would be:
Would it be better for us to test against an environment with a contrived theme that will not change? I sense that the control in this experiment is dynamic.

**Comment by bsessions85** [comment]
> If I understand this correctly, the values in the selectors need to change because the default theme for WordPress changed.
> 
> I suppose the next logical question would be: Would it be better for us to test against an environment with a contrived theme that will not change? I sense that the control in this experiment is dynamic.

Yeah, that is a good point. I'll look in to that now.

**Comment by GaryJones** [comment]
If something else in WP Core changed (like a selector in the media uploader), then you'd have to make changes anyway.

In this case, it looks like only two strings are needing to be changed, and that's because the default theme is now one that supports full-site editing; the now-replaced `entry-title` has been around for many many years - see [this](https://themes.trac.wordpress.org/browser/twentyten/1.0.3/single.php?rev=12716) from 12 years ago, and there are probably earlier examples too.

Creating and maintaining a contrived theme that still takes advantage of new WP core features that validate how customers and the code in this repo would be expected to engage with it, doesn't seem like the best use of time.

**Comment by jesse-greathouse** [comment]
> Creating and maintaining a contrived theme that still takes advantage of new WP core features that validate how customers and the code in this repo would be expected to engage with it, doesn't seem like the best use of time.

Yea that makes sense. Thanks for answering.

**Pull request merged**
