### PR TITLE
Fix ESLint issues in Search Dev Tools

### PR DESCRIPTION
**Pull request by rinatkhaziev**
## Description

Somewhere along the way eslint got borked via one of renovatebot merges, this should address.

### Internal coding standards improvements

We've fixed ESLint configs in one of our mu-plugins

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1.  Merge and `cd  search/search-dev-tools`
2.  `npm run lint` and ensure ESLint runs successfully.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
cc @pschoffer

**Comment by pauarge** [comment]
Do we want to use this PR to also bump to the latest version of ESLint and its dependencies?

**Review by pschoffer — CHANGES_REQUESTED** [review]
Now I get (after reinstaling dependencies):
```
 npm run lint

> search-dev-tools@1.0.0 lint /home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools
> eslint src


/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/components/app.js
  27:4   error  Missing JSDoc parameter description for 'props'  valid-jsdoc
  44:18  error  'document' is not defined                        no-undef

/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/components/collapsible-list/index.js
  20:73  warning  Identifier name 'i' is too short (< 2)  id-length

/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/components/information-pane/index.js
  30:4  error  Missing JSDoc parameter description for 'props'  valid-jsdoc

/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/components/overlay/index.js
  10:4   error  Missing JSDoc parameter description for 'props'  valid-jsdoc
  27:87  error  Trailing spaces not allowed                      no-trailing-spaces

/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/components/query/index.js
   10:1   error    More than 1 blank line not allowed            no-multiple-empty-lines
   38:4   error    Trailing spaces not allowed                   no-trailing-spaces
   42:39  error    'url' is already declared in the upper scope  no-shadow
   50:12  error    There must be a space after this paren        space-in-parens
  140:3   error    Trailing spaces not allowed                   no-trailing-spaces
  151:19  warning  Identifier name 'q' is too short (< 2)        id-length

/home/pavel/git/automattic/vip-go-mu-plugins/search/search-dev-tools/src/webpack-public-path.js
  4:76  error  Newline required at end of file but not found  eol-last

✖ 13 problems (11 errors, 2 warnings)
  6 errors and 0 warnings potentially fixable with the `--fix` option. npm run lint

 ```
 
 Do you get the same? Should we fix those issues or leave it a seperate pr?

**Comment by rinatkhaziev** [comment]
> Do you get the same? Should we fix those issues or leave it a seperate pr?

Yeah, I think separate, I was going back and forth between whether to fix them or leave for the next one.

**Comment by rinatkhaziev** [comment]
> Do we want to use this PR to also bump to the latest version of ESLint and its dependencies?

@pauarge I thought about but wanted to get it to a stable place first before trying to bump all of them. There's a non-zero chance it will break with the latest dependencies in wpvip-eslint-config

**Review by pschoffer — APPROVED** [review]

**Comment by pschoffer** [comment]
No production code change => no deploy needed.
(moved the bew `/.babelrc.json` to deploy ignore in https://github.com/Automattic/vip-go-mu-plugins/pull/2260 )

**Pull request merged**
