### PR TITLE
Update drop-ins/object-cache to wp-memcached@8112438

### PR DESCRIPTION
**Pull request by rinatkhaziev**
## Description

This PR updates drop-ins/object-cache/object-cache.php to [wp-memcached@8112438](https://github.com/Automattic/wp-memcached/blob/811243804a892a4609a4581d9479fa80c4e4ac8d/object-cache.php) to reach code parity.

Please note, currently,  object-cache.php is not loaded from `drop-ins/`

### Update wp-memcached in drop-ins

Update the reference to the wp-memcached submodule to the version running in production (v3.2.2)

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples. 

## Steps to Test

The code is not loaded anywhere ATM.

### CODE REVIEW

**Comment by jenkoian** [comment]
Dupe of https://github.com/Automattic/vip-go-mu-plugins/pull/1350 but this one is probably more up to date so feel free to close the other 👍

**Review by nickdaugherty — APPROVED** [review]
Looks good. Do we want to run this as a subtree instead of a submodule?

**Comment by rinatkhaziev** [comment]
@nickdaugherty good point about the subtree, I'll merge as-is and then we can revisit the whole drop-ins situation and use the subtree.

**Comment by nickdaugherty** [comment]
r1444-stacks

**Comment by nickdaugherty** [comment]
Release v1.22.0

**Pull request merged**
