### PR TITLE
No index non production sites with a custom domain

### PR DESCRIPTION
**Pull request by chrean**
Discussed here: https://github.com/Automattic/vip-go-mu-plugins/issues/904

### CODE REVIEW

**Comment by joshbetz** [comment]
r112439-deploy

**Comment by mjangda** [comment]
One small downside with this implementation is that it will add the tag to local development environments as well. Not sure if that's an issue but could be unexpected for some devs?

**Comment by chrean** [comment]
Can't see why a dev may want to index a local environment, however I agree, it may be unexpected and perhaps confusing?

If so, we may add a check on `WPCOM_IS_VIP_ENV` e.g. 

```
if ( 'production' !== VIP_GO_ENV && WPCOM_IS_VIP_ENV ) {
                $headers['X-Robots-Tag'] = 'noindex, nofollow';
}

**Comment by mjangda** [comment]
Could also do `false !== VIP_GO_ENV && 'production' !== VIP_GO_ENV`.

This also feels dangerous and would be good to add some tests :)

**Pull request merged**
