### PR TITLE
Trigger warning for alloptions fallback cache

### PR DESCRIPTION
**Pull request by WPprodigy**
Help debug the sites struggling with alloptions

### CODE REVIEW

**Comment by renatonascalves** [comment]
One inconvenience of this change is that it will exit with status code other than 0. Particularly in a CI environment (Github Action, Buddy, etc).

It also pollutes the logs with those warnings.

```
Warning: VIP: Saving to alloptions fallback cache. in /buddy/site.com/.buddy-tests/wordpress/wp-content/mu-plugins/001-core/options-api.php on line 67
```

**Comment by WPprodigy** [comment]
Ah, wasn't aware of that effect.

I've been auditing the errors and figuring out the next steps towards resolving the common causes (looking at you, rewrite_rules and user_roles). Have also found this error to be quite helpful when issues are ongoing as it helps you see where constant (and usually problematic) option writes are coming from.

Will probably remove it eventually, but for now would it be sufficient to hide it behind a check like this?

```
if ( defined( 'WPCOM_IS_VIP_ENV' ) && true === WPCOM_IS_VIP_ENV ) {
  trigger_error( 'VIP: Saving to alloptions fallback cache.', E_USER_WARNING );
}
```

**Comment by renatonascalves** [comment]
@WPprodigy That would be ideal. 

This constant is not set in a CI context and would only work on VIP environments.

**Comment by renatonascalves** [comment]
On a related note: apparently the problem was/is being caused by the `object-cache.php` file. More specifically, the location of the file.

We install that file from [here](https://github.com/alleyinteractive/mantle-ci/blob/develop/install-wp-tests.sh#L390-L393).

There might be some differences between this one and the version VIP falls back to. I'd still recommend adding the conditional though, so that this error is only logged in a VIP environment.

**Comment by bartoszgadomski** [comment]
Hi @WPprodigy, thank you for your work on this.

After inspecting the CI logs for unit tests, we saw thousands of occurrences of the mentioned warning (`Warning: VIP: Saving to alloptions fallback cache. in /var/www/html/wp-content/plugins/vendor/automattic/vip-go-mu-plugins/001-core/options-api.php on line 67`). If that could be triggered on a VIP environments only, that would be great 🙂

**Comment by WPprodigy** [comment]
Added here: https://github.com/Automattic/vip-go-mu-plugins/pull/4759

**Pull request merged**
