### PR TITLE
Site Details: Include plugins that are enabled sitewide

### PR DESCRIPTION
**Pull request by netsuso**
## Description

We are currently fetching the list of enabled plugins with `get_option( 'active_plugins' )`, but this is not taking into account plugins that are "network active" on a multisite. This PR checks also `get_site_option( 'active_sitewide_plugins' )`, and adds an extra flag `enabled_sitewide` to indicate whether a plugin is enabled network wide.

### Include sitewide plugins in site details

We keep improving the site details data we are gathering from all sites to have more information about multiple runtime variables. This time, we are including the list of plugins enabled sitewide on multisite installations, as we were only considering plugins enabled locally for a site.

## Checklist

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples. 

## Steps to Test

1. Check out PR on a Go Sandbox
1. Execute `wp cron-control events list` and find the id for the entry `vip_config_sync_cron`
1. Run it manually with `wp cron-control events run <id>`
1. Check the output in `/chroot/tmp/logstash.log` and ensure the new field `enabled_sitewide` is present

### CODE REVIEW

**Review by rinatkhaziev — CHANGES_REQUESTED** [review]
A couple of notes: 

`sitewide` is a bit confusing since in WP terminology it's called "network-wide", I think to avoid confusion we should stick to `network` because it's a well-known term, `sitewide` is ambiguous, because it's called "Multisite network" that consists of subsites.

Also, what do you think about introducing a new field have it as `enabled_via=code|network|local`? 

This would marginally improve filtering (you would only ever need to filter by this field instead of the current two).

**Comment by netsuso** [comment]
> `sitewide` is a bit confusing since in WP terminology it's called "network-wide", I think to avoid confusion we should stick to `network` because it's a well-known term, `sitewide` is ambiguous, because it's called "Multisite network" that consists of subsites.
> 
> Also, what do you think about introducing a new field have it as `enabled_via=code|network|local`?
> 
> This would marginally improve filtering (you would only ever need to filter by this field instead of the current two).

- Renamed "sitewide" to "network"
- After some discussion in Slack, added an `activated_by` field (ah, naming things... :D)

**Review by rinatkhaziev — APPROVED** [review]
:shipit:

**Review by rinatkhaziev — APPROVED** [review]

**Comment by netsuso** [comment]
stacks-r1439

**Comment by nickdaugherty** [comment]
Release v1.22.0

**Pull request merged**
