### PR TITLE
Update Jetpack-9.3 subtree to the final 9.3 release

### PR DESCRIPTION
**Pull request by netsuso**
## Description

Update `jetpack-9.3` subtree to the final Jetpack 9.3 release.

### Plugin Updated: Jetpack 9.3

We have upgraded Jetpack 9.3 to the final Jetpack 9.3 release.

Although this new version will be rolled out to all sites on Thursday 14th, remember you can start testing it in your site by adding this constant to your `vip-config.php` file: `define( 'VIP_JETPACK_PINNED_VERSION', '9.3');`

## Checklist

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] (For Automatticians) I've created a changelog draft. 

## Steps to Test

1. Check out PR.
1. Add constant `define( 'VIP_JETPACK_PINNED_VERSION', '9.3' );`
1. Go to the Jetpack dashboard in wp-admin and ensure that the version is `9.3`
1. Ensure everything works as expected

### CODE REVIEW

**Comment by nickdaugherty** [comment]
@netsuso the `bin` and `tools` directories came back in this PR. I had attempted to [ignore those here](https://github.com/Automattic/vip-go-mu-plugins/blob/cb530c9e1e9195adb8172b6b71238babc5ece9c6/.gitignore#L23-L24), but maybe that's not working?

**Review by nickdaugherty — CHANGES_REQUESTED** [review]
The bin and tools directories came back - we need to not be committing / deploying those.

**Comment by netsuso** [comment]
> @netsuso the `bin` and `tools` directories came back in this PR. I had attempted to [ignore those here](https://github.com/Automattic/vip-go-mu-plugins/blob/cb530c9e1e9195adb8172b6b71238babc5ece9c6/.gitignore#L23-L24), but maybe that's not working?

:thinking: I'm afraid that with subtrees we cannot control what cannot be committed and what cannot, as it's effectively a merge from another branch. I'll have a look...

**Comment by netsuso** [comment]
> The bin and tools directories came back - we need to not be committing / deploying those.

I've changed the `add-jetpack-subtree.sh` so `bin/` and `tools/` are removed after creating the subtree. As the updates work as a merge, it seems they will be kept removed on updates, although I bet there can be merge conflicts sometimes (if they change anything on those directories upstream)

**Comment by rinatkhaziev** [comment]
I think we might want to add those to `.deployignore` instead?

**Review by nickdaugherty — APPROVED** [review]
Thank you for removing the `tools` and `bin` directories!

**Comment by netsuso** [comment]
stacks-r1332

**Comment by netsuso** [comment]
Release v1.5.0

**Pull request merged**
