### PR TITLE
Search: Fix is_cli logic in filter__ep_do_intercept_request

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description
Follow up to #2719, let's define `$is_cli` before doing the check to assign the request URI for the 401 logging.

### CODE REVIEW

**Review by pschoffer — APPROVED** [review]

**Review by pschoffer — CHANGES_REQUESTED** [review]
This is a quite small change but what do you think about adding changelog entry if it is touching production code?

**Comment by rebeccahum** [comment]
I don't think it's necessary since it's just for our own logging purposes of 401s — it doesn't touch any client functionality otherwise.

**Review by rinatkhaziev — APPROVED** [review]

**Comment by rebeccahum** [comment]
r2128-stacks

**Comment by sjinks** [comment]
v20211228.1

**Pull request merged**
