### PR TITLE
Update Rewrite Rules Inspector

### PR DESCRIPTION
**Pull request by pschoffer**
## Description
Update [Rewrite-Rules-Inspector](https://github.com/Automattic/Rewrite-Rules-Inspector) to the latest version.

### Plugin Updated: Rewrite Rules Inspector

Update of Rewrite Rules Inspector plugin. The licence file was added.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Verify that VIP -> Rewrite inspector still works.

### CODE REVIEW

**Comment by GaryJones** [comment]
I would say to hold off on this - it doesn't look like it has pulled in the [most recent change](https://github.com/Automattic/Rewrite-Rules-Inspector/commit/0453d1a6b659cd98604dd024081466edc2008e7c), and I'm hoping to get a few other items tidied up for a 1.3.0 release.

It's great that you're on top of these changes, but there's nothing critical/substantial in there, and this repo was already running newer than the latest tagged release anyway.

**Comment by pschoffer** [comment]
Oh ok that sounds great, thanks @GaryJones for the input! I will drop this then and reopen it after we get a new "alert" about a change in that plugin.

**Comment by GaryJones** [comment]
@pschoffer 1.3.0 and then [1.3.1](https://github.com/Automattic/Rewrite-Rules-Inspector/releases/tag/1.3.1) have been released.

**Comment by pschoffer** [comment]
Thanks @GaryJones, I'll pull it in.

**Pull request closed without merging**
