### PR TITLE
Bump vip-support to 7f39c46: Add add_role actions during WP CLI requests

### PR DESCRIPTION
**Pull request by htdat**
## Description

Relevant PR https://github.com/Automattic/vip-support/pull/91

By running this action during WP-CLI requests, we can avoid front-end writes and make sure VIP Support roles and users are added properly through Admin VIP Console. 

The detailed approach is discussed here https://github.com/Automattic/vip-support/issues/90#issuecomment-801691535 with a small change to the `wp_loaded` hook. 

### Bump vip-support to 7f39c46 

Add add_role actions during WP CLI requests

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

### Single site 

1. Reset your VIP Go testing site: 
```
wp option delete wp_user_roles
wp role reset --all 
wp option delete vipsupportrole_version
wp role list
```

2. Verify that the last command does not have any VIP support role. 
3. Switch to this folder in your sandbox: `cd ~/software-stacks/mu-plugins/1/vip-support` 
4. Apply the patch https://github.com/Automattic/vip-support/pull/91.patch
5. Run `wp role list`. It should include two VIP Supported roles. 

### Sub-sites in a multi-site network 

1. Create a VIP Go multi-site or an existing site like this site ID `358`. 
2. Switch to this folder in your sandbox: cd ~/software-stacks/mu-plugins/1/vip-support
3. Apply the patch https://github.com/Automattic/vip-support/pull/91.patch
2. Create a new sub-site `wp site create --slug=subsite-2`.
5. Run `wp role list --url=http://EXAMPLE.go-vip.co/subsite-2/`
6. Verify that two VIP Supported roles are there.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
Hi @htdat, please update the PR according to the PR template. I.e. include the Description, Changelog description, Steps to test, and the Checklist.

Thank you.

**Comment by htdat** [comment]
@rinatkhaziev I've updated the PR. I hope it's OK now 👍

**Review by nickdaugherty — APPROVED** [review]

**Comment by nickdaugherty** [comment]
r1494-stacks

**Comment by nickdaugherty** [comment]
Release v1.35.0

**Pull request merged**
