### PR TITLE
Update old domains and WordPress.com references

### PR DESCRIPTION
**Pull request by GaryJones**
## Description

There have been several changes recently that have not been reflected in the URLs in this repo.

- Much documentation now lives at https://docs.wpvip.com
- Main marketing site has changed from vip.wordpress.com to wpvip.com
- Branding has changed from "WordPress.com VIP" to "WordPress VIP".

This change updates each instance as needed.

Some URL references have been deleted where it makes sense, and an instance around the "Powered By WordPress.com VIP" has been left as that has wider implications that are being handled elsewhere.

## Changelog Description

Updated old documentation URLs, and WordPress.com VIP references, in code comments and some customer-facing strings.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).
- [ ] (For Automatticians) I've created a changelog draft. 

## Steps to Test

Each old `vip.wordpress.com` references was manually tested to see where it redirected to, and then that was considered to see if it was a good replacement. For those without a successfull redirect, a replacement was manually found. If a suitable replacement couldn't be found, then the reference was deleted.

1. Review the URL changes to ensure that they make sense.

### CODE REVIEW

**Comment by joshbetz** [comment]
I think we should leave the existing plugin authors in place. We can add WPVIP or Automattic to the list where it's missing though.

**Comment by GaryJones** [comment]
> I think we should leave the existing plugin authors in place. We can add WPVIP or Automattic to the list where it's missing though.

Fair point. Restored in the [one place](https://github.com/Automattic/vip-go-mu-plugins/pull/1911/files?w=1#diff-8e40e9c2f54300eddfde544e080e3de515f4db01f52ee641f87488c8fab179f6R7) I'd changed it.

**Review by brandon-m-skinner — APPROVED** [review]
Looks great. Thanks for the update @GaryJones ❤️.

**Comment by netsuso** [comment]
stacks-r1308

**Pull request merged**
