### PR TITLE
Include the original ElasticSearch query and backtrace when logging errors

### PR DESCRIPTION
**Pull request by netsuso**
## Description

When an ElasticSearch query fails or it returns a warning, Include the full original query in the message sent to logstash.

### Improve logging for ElasticSearch failed queries

When a VIP Search query fails, it gets logged to Logstash so we can investigate the problems. Now we are also logging the full query sent to ElasticSearch and the PHP backtrace, so we can have much more detailed information about the root cause.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] (For Automatticians) I've created a changelog draft.

### CODE REVIEW

**Comment by netsuso** [comment]
First I had only added the query, but now I've also added the PHP backtrace. I'm not sure if we will obtain a lot of useful info from there, but it's worth trying

**Comment by rinatkhaziev** [comment]
@netsuso since this changes the signature of `ep_handle_failed_request`, are we absolutely sure we updated the calls accordingly everywhere?

**Comment by netsuso** [comment]
> @netsuso since this changes the signature of `ep_handle_failed_request`, are we absolutely sure we updated the calls accordingly everywhere?

This is actually a helper method, the code was initially inside `filter__ep_do_intercept_request`, but it was extracted to avoid having a big method.

It should actually be private, I think it's public so it can be tested :man_shrugging: 

But anyway, I've just checked the full `mu-plugins` code and there aren't any more references

**Review by rinatkhaziev — APPROVED** [review]
:shipit:

**Comment by brandon-m-skinner** [comment]
r1350-stacks (staging)

**Comment by netsuso** [comment]
Release v1.9.0: https://github.com/Automattic/vip-go-mu-plugins/releases/tag/v1.9.0

**Pull request merged**
