### PR TITLE
Adding CI test cases with disabled Jetpack

### PR DESCRIPTION
**Pull request by pauarge**
## Description

This PR adds two test cases in Circle CI to test mu-plugins with disabled Jetpack. This should cover issues such https://github.com/Automattic/vip-go-mu-plugins/pull/2096.

### Internal: Improved Jetpack automated testing

Added test cases to test mu-plugins when Jetpack is disabled.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

You should see the newly added steps in this PR already.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
Thank you for adding these! 

I wonder, though, whether it's beneficial to have the multisite counterpart?

/cc @netsuso @pschoffer

**Comment by pauarge** [comment]
AFAIK build steps run in parallel, so there is not a big time difference in having or not multisite. I've added it because it doesn't hurt to also test in that case, but we can safely remove it @rinatkhaziev.

**Review by netsuso — APPROVED** [review]
Looks good to me, thank you!

**Comment by netsuso** [comment]
No deploy required

**Pull request merged**
