### PR TITLE
ci: Add PHP 8.3 to the Matrix

### PR DESCRIPTION
**Pull request by sjinks**
PHP 8.3 alpha is out, and seeing how it works with our plugins is interesting.

This PR adds PHP 8.3 for WP nightly to the Matrix.

### CODE REVIEW

**Comment by GaryJones** [comment]
Can you please explain why "test: Mock http_response_code()" was needed for this CI bump?

**Review by rebeccahum — APPROVED** [review]

**Comment by sjinks** [comment]
@GaryJones `http_response_code()` seems to behave differently in PHP 8.3 (I haven't checked its source code, though): it fails with `Headers already sent` if the script has printed something to the output (like "Installing WordPress..."). This didn't happen in 8.2. Thus, I had to mock that function for the tests to pass.

**Comment by sjinks** [comment]
This is it: https://heap.space/xref/php-src/ext/standard/head.c?r=3af5f47c#366

It didn't happen in 8.2: https://heap.space/xref/PHP-8.2/ext/standard/head.c?r=a6a5d467#355

**Comment by sjinks** [comment]
Failed tests: https://github.com/Automattic/vip-go-mu-plugins/actions/runs/5255758235/jobs/9496113130#step:5:329

**Pull request merged**
