### PR TITLE
Upgrade to Jetpack 8.8.1

### PR DESCRIPTION
**Pull request by netsuso**
## Description

Upgrade Jetpack 8.8.1

## Checklist

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- n/a This change has relevant unit tests (if applicable).
- n/a This change has relevant documentation additions / updates (if applicable).

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Just noting that this has been rescheduled for Thursday the 13th at 15:00 UTC.

**Comment by brandon-m-skinner** [comment]
@netsuso 

Gonna need to be updated for the new Jetpack release https://github.com/Automattic/jetpack/releases/tag/8.8.1

**Comment by netsuso** [comment]
Tested on local env and in a sandbox. The dashboard is correctly shown in both of them. No JS errors

**Comment by netsuso** [comment]
stacks-r1067

**Pull request merged**
