### PR TITLE
Refresh PHPCS configuration

### LINKED ISSUE #1032: Switch to new VIP-Coding-Standards PHPCS rules
As [noted](https://github.com/Automattic/vip-go-mu-plugins/pull/766#issuecomment-444111235) by @GaryJones, this repo is still on the old PHPCS rules - we should switch over to https://github.com/Automattic/VIP-Coding-Standards instead, which is where active development is going.

### PR DESCRIPTION
**Pull request by GaryJones**
## Description

Update the PHPCS configuration. See the individual commits for more info, but feel free to squash when merging.

Fixes #1032.

Note that PHPCS is not run as part of Travis as this was [removed](https://github.com/Automattic/vip-go-mu-plugins/commit/8ac02327ec9162d8cd3b6f363e9332ceca87582e), so there will be no effects on builds / jobs for other PRs. There will need to be some tidy-up for this to pass successfully:

 - At severity 1, there are 354 errors and 773 warnings.
 - At severity 5, there are 342 errors and 554 warnings.
 - At severity 6, there are 32 errors and 130 warnings.

Included in this are some PHPCompatibilityWP issues, which are worth fixing sooner rather than later, in a different PR. Work on fixing those, and other violations will be easier to start once this PR is merged.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] N/A This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Check out PR.
1. Run `composer install` to add in the PHPCS standard packages. They will automatically register themselves to the PHPCS install.
1. Run `phpcs` (with optional flags like `--severity=6` or `--report=summary`).

### CODE REVIEW

**Comment by mjangda** [comment]
> Note that PHPCS is not run as part of Travis as this was removed,

I'd like to implement a transitional approach to this for Circle CI similar to what @cojennin implemented for Edit Flow: https://github.com/Automattic/Edit-Flow/pull/559

**Comment by GaryJones** [comment]
@batmoo @cojennin While great in theory, that's not how PHPCS works - nearly all sniffs presume the whole file is there, or that at least the whole of the _scope_ for a token is present.

For instance, in this [NonceVerificationSniff](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/Security/NonceVerificationSniff.php) if [one of four superglobals](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/Security/NonceVerificationSniff.php#L37-L40) is accessed, then it will [check for a nonce](https://github.com/WordPress/WordPress-Coding-Standards/blob/31b8d9bde28b49caf8113db48955cf840cb76504/WordPress/Sniff.php#L1437), by considering what scope it is in, finding the start of that scope, and then seeing if any of the [nonce check functions](https://github.com/WordPress/WordPress-Coding-Standards/blob/31b8d9bde28b49caf8113db48955cf840cb76504/WordPress/Sniff.php#L120-L124) appear before the superglobal, in that scope. There's a bit more to it than that, but that's the simplified version.

If the lines that changed does not include the start of the scope, or maybe not the part that includes the nonce check functions, then incorrect results will appear.

You've only got to look at the [number of `findPrevious()`](https://github.com/Automattic/VIP-Coding-Standards/search?q=findPrevious&unscoped_q=findPrevious) calls, and [`findNext()` calls](https://github.com/Automattic/VIP-Coding-Standards/search?q=findNext&unscoped_q=findNext) in VIPCS, to appreciate that while these find calls can handle tokens being on the next line (they should typically exclude all whitespace, including linebreaks, when looking for a token, to make them code-style agnostic), **if** the next line is not available to PHPCS, then we can't have the confidence that the checks are correctly catching a violation, or that a caught "violation" is not a false positive that is un-necessarily blocking passing CI checks.

What would be be possible, is calculating a list of just the changed _files_, and having PHPCS run against them. Untested, but something like:

```sh
FILES=$(git ls-files -om --exclude-standard);
if [ -n "$FILES" ]; then
	phpcs "$FILES"
fi
```

That would still mean having to actively address PHPCS violations in a way that I know you're trying to avoid, but just looking for [new] violations on changed _lines_ is unreliable.

cc @jrfnl

**Comment by jrfnl** [comment]
> but just looking for [new] violations on changed lines is unreliable.

I completely concur. 

> What would be be possible, is calculating a list of just the changed files, and having PHPCS run against them.

Or use the new `--filter=gitstaged` option in a git commit hook ?

**Comment by cojennin** [comment]
Miscommunication on my part, apologies! [PHPCS is run over the entirety of the project](https://github.com/Automattic/Edit-Flow/blob/master/bin/phpcs-diff.sh#L11), `coverageChecker` is just doing [an intersection of the line numbers](https://github.com/exussum12/coverageChecker/blob/master/src/CoverageCheck.php#L42) of the diff output and phpcs output.

Sorry!

**Pull request merged**
