### PR TITLE
Add meta_key_value index

### PR DESCRIPTION
**Pull request by joshbetz**
Add an index on the postmeta.meta_value for all new sites.

### CODE REVIEW

**Comment by mjangda** [comment]
@joshbetz I thought about it some more and decided that this is probably the best approach :)

I added a test so we can catch if/when our `dbDelta` addition fails. Also adds a prefix to the index name and removes the default `meta_key` index.

**Comment by ethitter** [comment]
Tested fine in my local environment. :shipit:

**Comment by joshbetz** [comment]
Looks good to me too. I can't "review" this because it's my PR.

> I added a test so we can catch if/when our dbDelta addition fails.

Yeah, that's a good call.

**Comment by joshbetz** [comment]
Once we test the index on some existing sites, I'll merge and deploy.

**Comment by mjangda** [comment]
I think we can merge this now; INDEX has been live on a bunch of sites now.

**Comment by joshbetz** [comment]
r89253-deploy

**Pull request merged**
