### PR TITLE
Bump Jetpack submodule to 11.2

### PR DESCRIPTION
**Pull request by rinatkhaziev**
## Description

This concludes the process of gradually bringing up the Jetpack submodule to the latest.

See #3492 #3287 

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Nothing to test

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
This will come handy with #3503

**Review by jesse-greathouse — APPROVED** [review]
👍

**Comment by renatonascalves** [comment]
Just a quick notice that I started to see errors with a conflict of versions after this update:

```
Fatal error: Cannot declare class Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ11_2\Autoloader, because the name is already in use in /wordpress/wp-content/mu-plugins/jetpack/vendor/jetpack-autoloader/class-autoloader.php on line 15
```

It looks like both the `jetpack` and `jetpack-11.2` plugins are using the same namespace. This is mainly affecting unit tests, the site itself is not being affected.

**Comment by rinatkhaziev** [comment]
@renatonascalves, thanks for reporting. Do you mind sharing more about the context?

We don't load anything from `jetpack` by default. It's merely for legacy purposes because some folks have direct includes. I'm assuming something like that is happening in your tests?

**Comment by renatonascalves** [comment]
Thanks for reaching out. I’m not intentionally loading jetpack directly though. 🤔  I’ll do a bit of digging to see what could be loading it.

This is however only happening while running unit tests (PHPUnit).

**Pull request merged**
