### PR TITLE
Account for array-style query vars

### PR DESCRIPTION
**Pull request by trepmal**
See #1087

## Description

When `category[]=term` appears in a URL, the array-style causes a lot of warnings.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Coming soon. Maybe.

### CODE REVIEW

**Comment by brandon-m-skinner** [comment]
@trepmal is this PR still valid? If so I'd like to pursue its completion/deployment.

**Comment by trepmal** [comment]
I'm not really sure how big of an issue this is anymore. Year-ago-me didn't leave enough notes for today-me to look this up :(

Since this is part of a deprecated shared plugin, I suspect the issue is still valid, but fairly infrequent.

**Comment by brandon-m-skinner** [comment]
@trepmal Do you want to pursue completion or close it?

**Comment by trepmal** [comment]
Probably safe to close. Can't find any evidence that this is triggering warnings currently.

**Pull request closed without merging**
