### PR TITLE
Update wp-memcached submodule.

### PR DESCRIPTION
**Pull request by jenkoian**
## Description

The object-cache drop in hasn't been updated for a while and there's
been an important fix for the `$found` parameter added.

This is particularly important for some plugins, e.g. MLP3 depends on this functionality and performance declines without it.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Install MLP3
2. Notice a number of queries constantly being run on the homepage
3. Update the submodule to this PR
4. The queries should now be gone as the cache should be getting hit.

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Thanks for the PR @jenkoian!

The issue with `$found` is not fully fixed upstream in `wp-memcached` - after merging the original PR (https://github.com/Automattic/wp-memcached/pull/34), I identified an unresolved bug in the implementation, which I documented here:

https://github.com/Automattic/wp-memcached/issues/40

So, that still needs to be addressed before we can update to the latest, or we'll likely cause more problems than we solve.

**Comment by jenkoian** [comment]
Thanks for the response @nickdaugherty!

This is quite frustrating. The contract of the original methods (https://developer.wordpress.org/reference/functions/wp_cache_get/) and (https://developer.wordpress.org/reference/classes/wp_object_cache/get/) says there should be a 4th parameter of `$found` so I can understand why MLP3 are using this. (unfortunately this version of their plugin is not open source so I cannot link to it).

I can open a support ticket with them, but in general I would have expected that the drop in would support the contract of the documented function.

Is there any progress being made on this issue do you know? I'm happy to take a look too after the weekend. 

Thanks!

**Comment by jenkoian** [comment]
Just for reference, hopefully a fix for https://github.com/Automattic/wp-memcached/issues/40 in this PR: https://github.com/Automattic/wp-memcached/pull/43

**Comment by jenkoian** [comment]
@nickdaugherty just updated this one too 👍

**Comment by rinatkhaziev** [comment]
Superseded by #2006

**Pull request closed without merging**
