### PR TITLE
Fix WPCOM_VIP_PRIVATE_DIR

### LINKED ISSUE #858: Fix WPCOM_VIP_PRIVATE_DIR when sandboxed
In 250ff0ab262eeabcdae2394465188072e2afb08c, we added a conditional for `WPCOM_VIP_PRIVATE_DIR`, changing the path if we're sandboxed. The path for web requests on sandboxes should be the same as production. It's only different if you're sandboxed and connected to the container as root.

### PR DESCRIPTION
**Pull request by joshbetz**
The private dir is only prefixed with `/chroot` if you're running a sandbox as root, which shouldn't really happen anymore. As it is, this can break some sites when sandboxed because web requests are never root.

Fixes #858

### CODE REVIEW

**Comment by joshbetz** [comment]
This was originally added in #699 as a workaround for WP-CLI issues in sandboxes. Since sandboxes are no longer run as root, this shouldn't be necessary.

I think the `VIP_GO_IS_CLI_CONTAINER` should also not be necessary, since CLI containers should not be running as root either.

**Comment by mjangda** [comment]
> which shouldn't really happen anymore

Platform sandboxes?

**Comment by rebeccahum** [comment]
I noticed that I've been getting the error for this a lot as well for some sandboxes:

```
Notice: Array to string conversion in /var/www/wp-content/mu-plugins/lib/wpcom-error-handler/wpcom-error-handler.php on line 60
```

**Comment by WPprodigy** [comment]
This issue seems to be breaking things in zd-81258. 

By "work locally", would that just be `WP_CONTENT_DIR . '/private'`?

**Comment by nickdaugherty** [comment]
> The private dir is only prefixed with /chroot if you're running a sandbox as root, which shouldn't really happen anymore.

Hmm might be missing something but on my ephemeral sandbox, the private directory is at `/chroot/private`.

**Comment by nickdaugherty** [comment]
Ah figured it out - the file is there, but when PHP runs it's chrooted, so the path in code should be just `/private`.

**Comment by WPprodigy** [comment]
Not 100% sure it's related, but I have been running into issues where `chroot` is inserting itself into places it should not be, and this issue seems most relevant.

In #81258-z, you'll see paths like `/chrootwp-content/themes/techcrunch-2017/` in the errors:

```
Notice: Undefined index: HTTP_HOST in /chroot/var/www/db-config.php on line 133 [$ /usr/local/bin/wp --path=/var/www/ tc-cb-update-cb-tags --type=organization] [/chrootwp-content/db.php:336 wpcom_vip_get_query_comment(), /chrootwp-content/db.php:798 hyperdb->run_callbacks(), /chrootwp-includes/wp-db.php:2380 hyperdb->query(), /chrootwp-includes/taxonomy.php:3568 wpdb->get_var(), /chrootwp-includes/taxonomy.php:2750 _split_shared_term(), /chrootwp-content/themes/techcrunch-2017/features/crunchbase/saving.php:67 wp_update_term(), /chrootwp-content/themes/techcrunch-2017/features/wp-cli/crunchbase/class-cb-update-cb-tags.php:166 TC\Crunchbase\Saving\save_cb_data_to_term(), /chrootwp-content/themes/techcrunch-2017/features/wp-cli/crunchbase/class-cb-update-cb-tags.php:113 TC\WP_CLI\Crunchbase\CB_Update_CB_Tags->update_tag(), TC\WP_CLI\Crunchbase\CB_Update_CB_Tags->__invoke(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:89 call_user_func(), WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:425 call_user_func(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Runner.php:353 WP_CLI\Dispatcher\Subcommand->invoke(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Runner.php:376 WP_CLI\Runner->run_command(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Runner.php:1102 WP_CLI\Runner->_run_command_and_exit(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23 WP_CLI\Runner->start(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/bootstrap.php:75 WP_CLI\Bootstrap\LaunchRunner->process(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/wp-cli.php:23 WP_CLI\bootstrap(), phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/boot-phar.php:8 include('phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/wp-cli.php'), /root/roles/docker-container-vip-web/usr/local/bin/wp:4 include('phar:///root/roles/docker-container-vip-web/usr/local/bin/wp/php/boot-phar.php')]
```

In #82048-z, I found logs with similar errors showing `chroot` just liked to insert itself into all the pathing ` /chrootwp-content/db.php:581`:

```
[Suppressed] Warning: fsockopen(): unable to connect to 192.0.98.80:3390 (Connection timed out) in /chroot/var/www/wp-content/db.php on line 1044 [$ /usr/local/bin/wp cron-control orchestrate runner-only get-info --format=json --allow-root --quiet --path=/var/www] [/chrootwp-content/db.php:1044 fsockopen(), /chrootwp-content/db.php:1065 hyperdb->check_tcp_responsiveness(), /chrootwp-content/db.php:581 hyperdb->get_server_state(), /chrootwp-content/db.php:791 hyperdb->db_connect(), /chrootwp-includes/wp-db.php:2488 hyperdb->query(), /chrootwp-content/mu-plugins/cron-control/includes/class-events-store.php:428 wpdb->get_results(), /chrootwp-content/mu-plugins/cron-control/includes/class-events-store.php:294 AutomatticWPCron_ControlEvents_Store->get_jobs(), /chrootwp-includes/class-wp-hook.php:288 AutomatticWPCron_ControlEvents_Store->get_option(), /chrootwp-includes/plugin.php:203 WP_Hook->apply_filters(), /chrootwp-includes/option.php:58 apply_filters('pre_option_cron'), /chrootwp-includes/cron.php:478 get_option(), /chrootwp-includes/cron.php:257 _get_cron_array(), /chrootwp-content/mu-plugins/jetpack/class.jetpack-heartbeat.php:43 wp_next_scheduled(), /chrootwp-content/mu-
```

**Comment by mjangda** [comment]
Pushed some tweaks for this:

- We handle local environments better now.
- We check to see which path exists and use that (ignoring the container type check).

**Comment by nickdaugherty** [comment]
r619-stacks

**Pull request merged**
