### PR TITLE
Search: Do not sync if index does not exist

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description
In the use case described in https://github.com/Automattic/vip-go-mu-plugins/pull/2687#issuecomment-988566800, we sync even if the index does not exist. This filter will kill syncing actions if the index does not exist for the indexable.

### Plugin Updated: Enterprise Search

Use `ep_sync_indexable_kill` filter to check if index exists before attempting to sync.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test
1) Using a multisite ES (not in network mode), create a new subsite
2) Verify that the index does not exist yet for it via `wp vip-search get-indexes`
3) Create a post
4) Repeat step 2 to ensure that an index does not get created

### CODE REVIEW

**Comment by rebeccahum** [comment]
Also, wanting to note that I was able to create an index successfully with the addition of this filter via `vip dev-env --slug example-site exec -- wp vip-search index --setup --url=http://subsite6.example-site.com` and then verified with `wp vip-search get-indexes` after.

**Review by sjinks — APPROVED** [review]

**Comment by rebeccahum** [comment]
@sjinks Resolved a conflict, can you please re-review? Thanks!

**Review by sjinks — APPROVED** [review]

**Comment by sjinks** [comment]
r2077-stacks

**Comment by sjinks** [comment]
v20211214.0

**Pull request merged**
