### PR TITLE
Update vip-support submodule to latest

### PR DESCRIPTION
**Pull request by nickdaugherty**
## Description

Updates the vip-support submodule:

Bump Mustache lib for security
Remove unused REST endpoints
Fix unit test suite
Add ability to restrict support users by email address

### VIP Support: User Access Restrictions

Restricting which VIP Support accounts are allowed to access the site is now possible via the `VIP_SUPPORT_USER_ALLOWED_EMAILS` constant, which is an array of email addresses allowed to use the VIP Support User system.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
1. `git submodule update`
1. Add yourself as a support user
2. Log in with that support user and visit WP Admin
3. Should have regular permissions
4. In `vip-config/vip-config.php`, add `define( 'VIP_SUPPORT_USER_ALLOWED_EMAILS', array() );` (no users allowed)
5. Should have no permissions (but still logged in)
6. In `vip-config/vip-config.php`, change the constant to `define( 'VIP_SUPPORT_USER_ALLOWED_EMAILS', array( '$YOUREMAILHERE' ) );`
7. Should have regular permissions again

### CODE REVIEW

**Review by WPprodigy — APPROVED** [review]

**Comment by WPprodigy** [comment]
Oh we're doing that here too? Will need to merge in the unit tests with the rest of mu unit tests.

**Comment by nickdaugherty** [comment]
Sorry @WPprodigy I accidentally pushed that code onto this branch, it was meant for a separate branch. I'm gonna fix it.

**Comment by nickdaugherty** [comment]
Fixed - the repo merge will be in a separate branch.

**Review by WPprodigy — APPROVED** [review]

**Review by sjinks — APPROVED** [review]

**Comment by nickdaugherty** [comment]
Follow-up to merge the external vip-support submodule into this repo: https://github.com/Automattic/vip-go-mu-plugins/pull/2850

**Pull request merged**
