### PR TITLE
Remove wpcom_vip_include_active_plugins()

### PR DESCRIPTION
**Pull request by scottsweb**
As discussed in #848

### CODE REVIEW

**Comment by brandon-m-skinner** [comment]
@scottsweb is this PR still valid? If so I'd like to pursue its completion/deployment.

**Comment by scottsweb** [comment]
I believe it would be still valid yes... might be good to double check with @nickdaugherty or @mjangda in case anything has changed.

**Comment by nickdaugherty** [comment]
We'd need to check again for any uses of the function across our own or client code first.

**Comment by brandon-m-skinner** [comment]
@nickdaugherty There's only one occurrence and it's a copy of the mu-plugins-built branch in a client repo https://github.com/wpcomvip/insidehook/blob/724da6dc7c26a7c4db5bc3c6980fde9b085fe877/mu-plugins/vip-plugins/vip-plugins.php#L268-L280

**Review by pauarge — APPROVED** [review]
LGTM

**Comment by pauarge** [comment]
It looks like the reference that @brandon-m-skinner mentions in the comment above no longer exists.

**Review by pauarge — CHANGES_REQUESTED** [review]
Actually, we probably should have to delete this: https://github.com/Automattic/vip-go-mu-plugins/blob/71552b9adeb42595fb1bc44f06cf25d4dde450cc/rest-api/vip-endpoints.php#L373

and this: https://github.com/Automattic/vip-go-mu-plugins/blob/71552b9adeb42595fb1bc44f06cf25d4dde450cc/rest-api/vip-endpoints.php#L343

**Comment by pauarge** [comment]
Noting that we found quite a few sites that would break if this would be merged.

**Comment by WPprodigy** [comment]
Next step is probably adding some deprecation notices/warnings in the methods we want to remove. Then we can traverse logs for a bit until we've knocked out all existing codebases that would cause a problem.

**Comment by WPprodigy** [comment]
Took another look. So as long as these two plugins still exist, we can't really remove this function as far as I can tell: https://github.com/Automattic/vip-go-mu-plugins/blob/83d7293cef0221ab753fbf262939988e0f74081d/vip-helpers/vip-utils.php#L1246-L1249

Going to close out this PR.

**Pull request closed without merging**
