### PR TITLE
Adds a CI pipeline for search-dev-tools

### PR DESCRIPTION
**Pull request by pschoffer**
## Description

This change adds a CI pipeline for search-dev-tools. The pipeline lints and builds the javascript code to verify correctness.

### No production code change

This changelog can be ignored

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

Check out the CI jobs run

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
This is awesome!

Should we maybe take it further and actually run the build on merge? This will eliminate the potential merge conflict situation.

**Comment by rinatkhaziev** [comment]
Additionally, it'd be cool to have it run on a merge of specifically Dev Tools, maybe GH actions support that kind of workflow?

**Comment by pauarge** [comment]
@rinatkhaziev I think this should run on all merges, not only Dev Tools. The PR is awesome, but I see in the not-so-far future that we could move this plus an actual build of the dependencies to GitHub Actions.

**Review by pauarge — APPROVED** [review]

**Comment by pschoffer** [comment]
@rinatkhaziev those are very good points. I thought about it, but then I chickened out :) As I realize I would have to detect the change only to Dev-tools for the build which I guess the mythical (for me) GH actions can do. I am thinking about merging this first and hopefully take it step further on next iteration.

**Comment by pschoffer** [comment]
No production code change -> no deploy needed.

**Pull request merged**
