### PR TITLE
Use `client-mu-plugins` instead of `plugins` for the alternative Jetpack codebase

### PR DESCRIPTION
**Pull request by simonwheatley**
Closes https://github.com/Automattic/vip-go-mu-plugins/issues/797

### CODE REVIEW

**Comment by simonwheatley** [comment]
We need to coordinate the merge and deployment of this with some documentation changes here:
https://vip.wordpress.com/documentation/vip-go/testing-jetpack-on-vip-go/

**Comment by nickdaugherty** [comment]
This should be fine because of the `require_once` - the client mu plugins loading code would already automatically be including the local copy of JP, but I suppose it's better to force load this early, at the same time regular Jetpack would be loaded, for consistency (vs delaying and allowing regular client-mu-plugins code to do it).

**Comment by nickdaugherty** [comment]
I guess the above would only apply on multisites.

**Comment by joshbetz** [comment]
r101621-deploy

**Pull request merged**
