### PR TITLE
Prevent alloptions checks from running during unit tests

### PR DESCRIPTION
**Pull request by srtfisher**
## Description

Ensure that we're not running a unit test when running the alloptions checks. When `mu-plugins` is installed locally this throws errors when we really don't care about `alloptions`.

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation).

### CODE REVIEW

**Comment by sjinks** [comment]
`WP_RUN_CORE_TESTS` is defined by the WordPress test suite ([1](https://github.com/WordPress/wordpress-develop/blob/5ae18c46d2604b244660d43af2117eb33bced0a4/tests/phpunit/includes/install.php#L12-L14), [2](https://github.com/WordPress/wordpress-develop/blob/5ae18c46d2604b244660d43af2117eb33bced0a4/tests/phpunit/multisite.xml#L16)), and it is not something we would like to disable when we [run that suite](https://github.com/Automattic/vip-go-mu-plugins/blob/develop/.github/workflows/core-tests.yml).

Maybe

```php
remove_all_filters( 'pre_wp_load_alloptions' );
```

would help in your case?

Or

```php
remove_filter( 'pre_wp_load_alloptions', 'Automattic\\VIP\\Core\\OptionsAPI\\pre_wp_load_alloptions_protections', 999 );
```

?

**Comment by sjinks** [comment]
I was unable to reproduce the issue:

```
> phpunit
 Install Rsync:  WordPress already installed at /tmp/wordpress
 Install Rsync:  Rsyncing /home/volodymyr/work/mantle-framework/ to /tmp/wordpress/wp-content/plugins/mantle-framework/...
 Install Rsync:  Installing plugin logger (https://github.com/alleyinteractive/logger/archive/refs/heads/develop.zip)...
The plugin logger is already installed.
 Install Rsync:  Installing plugin jetpack (12.4)...
The plugin jetpack is already installed.
 Install Rsync:  Finished rsyncing to /tmp/wordpress/wp-content/plugins/mantle-framework/ and working directory is now /tmp/wordpress/wp-content/plugins/mantle-framework
 Install Rsync:  Running /tmp/wordpress/wp-content/plugins/mantle-framework/vendor/bin/phpunit in /tmp/wordpress/wp-content/plugins/mantle-framework
 Install:  Using configuration file: /tmp/wordpress/wp-tests-config.php
sh: 1: /usr/sbin/sendmail: not found
 Install:  Running as single site... 
ℹ To run multisite, pass WP_MULTISITE=1 or set the WP_TESTS_MULTISITE=1 constant.
PHPUnit 10.5.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.10-2ubuntu1
Configuration: /tmp/wordpress/wp-content/plugins/mantle-framework/phpunit.xml

...................S....................Registering sniffs in the  standard... DONE (304 sniffs registered)
Creating file list... DONE (1 files in queue)
.....................   61 / 1290 (  4%)
.............................................................  122 / 1290 (  9%)
.......SS....................................................  183 / 1290 ( 14%)
.........S...................................................  244 / 1290 ( 18%)
.............................................................  305 / 1290 ( 23%)
.............................................................  366 / 1290 ( 28%)
...........................................................SS  427 / 1290 ( 33%)
.............................................................  488 / 1290 ( 37%)
.............................................................  549 / 1290 ( 42%)
[2024-04-18T06:26:50.239960+00:00] Mantle.ERROR:  {"blogId":1,"exception":"[object] (Mantle\\Http_Client\\Http_Client_Exception(code: 0):  at /tmp/wordpress/wp-content/plugins/mantle-framework/src/mantle/http-client/class-pending-request.php:638)"} []
.S...........................................................  610 / 1290 ( 47%)
.............................................................  671 / 1290 ( 52%)
.............................................................  732 / 1290 ( 56%)
.............................................................  793 / 1290 ( 61%)
.............................................................  854 / 1290 ( 66%)
.............................................................  915 / 1290 ( 70%)
.............................................................  976 / 1290 ( 75%)
............................................................. 1037 / 1290 ( 80%)
............................................................. 1098 / 1290 ( 85%)
............................................................. 1159 / 1290 ( 89%)
............................S................................ 1220 / 1290 ( 94%)
............................................................. 1281 / 1290 ( 99%)
.........                                                     1290 / 1290 (100%)

Time: 00:36.410, Memory: 183.00 MB

OK, but some tests were skipped!
Tests: 1290, Assertions: 4688, Skipped: 8.
```

If you explain how to reproduce it, I think we can come up with something that works for everyone :-)

**Comment by sjinks** [comment]
Anyway,

```diff
diff --git a/src/mantle/testing/wordpress-bootstrap.php b/src/mantle/testing/wordpress-bootstrap.php
index cd027b3c..35f84ea6 100644
--- a/src/mantle/testing/wordpress-bootstrap.php
+++ b/src/mantle/testing/wordpress-bootstrap.php
@@ -205,3 +205,5 @@ if ( isset( $_SERVER['REQUEST_TIME_FLOAT'] ) ) {
 if ( is_blog_installed() ) {
        Utils::delete_all_posts();
 }
+
+remove_filter( 'pre_wp_load_alloptions', 'Automattic\\VIP\\Core\\OptionsAPI\\pre_wp_load_alloptions_protections', 999 );
```

worked for me (at least, it removed the filter).

**Comment by srtfisher** [comment]
Wow, thank you for that really in-depth example! I wasn't expecting you to actually pull down our testing framework 😄.

Your example is what we were previously doing in the individual project's unit test bootstrap but I was still seeing the issue. The framework hasn't actually had the issue -- it's the projects that depend on it and use the framework that is throwing this error:

> Warning: VIP: Unable to query alloptions from database. in /buddy/client/.buddy-tests/wordpress/wp-content/mu-plugins/001-core/options-api.php on line 60

I'm going to plug in your suggestion into the framework, cut a new release, and then test it on the subsequent project to see how it goes.

**Comment by WPprodigy** [comment]
I'd be curious to learn where/why things are breaking if you do find out @srtfisher. Happy to adjust the alloptions mitigations logic if it makes sense.

**Comment by srtfisher** [comment]
Still running into this during our CI process:

CleanShot 2024-04-19 at 10 48 12@2x

I'm trying to figure out the right timing to get the alloptions migrations unhooked during unit testing. Will report back later today.

**Comment by srtfisher** [comment]
I am also only seeing this error when `VIP_GO_APP_ENVIRONMENT` isn't defined. When it is defined then the error doesn't occur. One thing I'm seeing is that a call to `get_option()` from our `client-mu-plugins` is causing this to occur.

Wondering if the faster solution here might be to just disable this code for unit tests. There is some existing checks in this project that use that constant: [1](https://github.com/Automattic/vip-go-mu-plugins/blob/b93840530b4a67fde032fc2a64c40dae9de8a982/misc.php#L10) [2](https://github.com/Automattic/vip-go-mu-plugins/blob/b93840530b4a67fde032fc2a64c40dae9de8a982/advanced-post-cache.php#L10) [3](https://github.com/Automattic/vip-go-mu-plugins/blob/b93840530b4a67fde032fc2a64c40dae9de8a982/000-vip-init.php#L323)

**Comment by srtfisher** [comment]
I did find a work around that I will be plugging into the testing library we use. It has the initial suggestion from @sjinks but wrapped in an action due to timing (fun!):

```php
tests_add_filter( 'vip_mu_plugins_loaded', function () {
	remove_filter( 'pre_wp_load_alloptions', 'Automattic\\VIP\\Core\\OptionsAPI\\pre_wp_load_alloptions_protections', 999 );
} );
```

**Pull request closed without merging**
