### PR TITLE
Update Akismet to v4.1.10

### PR DESCRIPTION
**Pull request by parkcityj**
## Description
Update Akismet plugin to version 4.1.10

### Plugin Updated: Akismet 4.1.10

We upgraded Akismet 4.1.9 to Akismet 4.1.10

- Simplified the code around checking comments in REST API and XML-RPC requests.
- Added rel=”noopener” to the widget link to avoid warnings in Google Lighthouse.
- Set the Akismet JavaScript as deferred instead of async to improve responsiveness.
- Improved the preloading of screenshot popups on the edit comments admin page.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
1. Go to `wp-admin`> make sure site works normally as expected, and Akismet is installed
1. Run `wp plugin list` to ensure latest version.

### CODE REVIEW

**Review by netsuso — DISMISSED** [review]
Looks good to me! :ship:

**Review by pauarge — CHANGES_REQUESTED** [review]
Thanks for the changes! It looks good, but we should also bump the version number manually on the `akismet.php` file in the root directory.

**Comment by parkcityj** [comment]
Updated!

**Review by pauarge — APPROVED** [review]
LGTM

**Pull request merged**
