### PR TITLE
Search Dev Tools: bump Prism.js version bump to 1.25.0

### PR DESCRIPTION
**Pull request by jesse-greathouse**
PR #2440 prompted upgrade due to security concerns (https://github.com/Automattic/vip-go-mu-plugins/pull/2440)

## Description
In #2440 we merged the updated version of Prism.js for Search Dev Tools. This PR includes the build artifacts relevant to that change.

### Plugin updated: Enterprise Search

We have updated Enterprise Search Dev Tools to use the latest version of Prism.js syntax highlighting for queries.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out.
1. Perform a search
1. Click on VIP dev tools in admin bar
1. Inspect search results. make sure syntax highlighting is correct on JSON payloads..

### CODE REVIEW

**Review by pauarge — CHANGES_REQUESTED** [review]
I see that the lockfile version has changed. Is it possible that you have npm 6 instead of npm 7 installed?

**Comment by jesse-greathouse** [comment]
> I see that the lockfile version has changed. Is it possible that you have npm 6 instead of npm 7 installed?

Yea I'm using npm 6. I guess it should be 7?

**Review by pauarge — APPROVED** [review]
Looks good!

**Comment by jesse-greathouse** [comment]
r1846-stacks

**Pull request merged**
