### PR TITLE
[NO REVIEW REQUIRED AT THIS TIME, DO NOT MERGE] Moving vip-dashboard repository to vip-go-mu-plugins

### PR DESCRIPTION
**Pull request by lyx**
## Description

Moving vip-dashboard repository files to vip-go-mu-plugins repository. Issue request #90.

https://github.com/Automattic/vip-dashboard/issues/90

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Check out PR.
1. Go to `wp-admin` > `Tools` > `Bakery`
1. Click on "Bake Cookies" button.
1. Verify cookies are delicious.

### CODE REVIEW

**Comment by lyx** [comment]
Checkboxes items:

 This change works and has been tested locally (or has an appropriate fallback).
  This change works and has been tested on a Go sandbox.
  This change has relevant unit tests (if applicable).
  This change has relevant documentation additions / updates (if applicable).

Have not be performed yet - does not need review just yet.

**Comment by rinatkhaziev** [comment]
Thanks for the PR!

If a PR is not ready for review please submit it as a "Draft PR". I just converted it to such so it doesn't ping us for a review. 

Additionally, seems there's a rogue `.DS_Store` in the PR that needs to be removed.

**Comment by GaryJones** [comment]
The PR also seems to include an update to the submodule, rather than a commit that replaces the submodule with vip-dashboard at the commit the submodule was at. (Adding any new commits from the vip-dashboard package that weren't yet in vip-go-mu-plugins, should be done in a new PR).

**Comment by mjangda** [comment]
I suggest a few different PRs for this:

1. PR to bump the submodule to the latest version (merge + deploy)
2. PR to remove the submodule (merge, no deploy)
3. PR to add the plugin as-is, i.e. no submodule (merge, shouldn't need deploy)

As part of 3 we may need to look at the build process since there's some grunt build steps involved, I believe. If it's a lot of effort to integrate, it might be better just to leave it as-is for now since the plugin doesn't change much (although, that could change in the future).

**Comment by rinatkhaziev** [comment]
Superseded by #2078 and #2079

**Pull request closed without merging**
