### PR TITLE
Change global From email to @wpvip.com

### PR DESCRIPTION
**Pull request by mjangda**
Not really relevant to use @wordpress.com anymore.

### Updated `From:` Email Address

We now send all emails from WordPress applications with the `From` header set to `donotreply@wpvip.com`.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- n/a This change has relevant unit tests (if applicable).
- n/a This change has relevant documentation additions / updates (if applicable).
- n/a I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
1. Go to `wp shell`
1. `wp_mail( 'your-email@gmail.com', 'Testing', 'More testing' );`
1. Verify that email comes from `donotreply@wpvip.com`.

### CODE REVIEW

**Review by jesse-greathouse — APPROVED** [review]
nice. 👍

**Review by rinatkhaziev — DISMISSED** [review]
@mjangda thanks for the PR! there's a merge conflict and tests are failing, can you please address it?

**Review by sjinks — APPROVED** [review]

**Review by jesse-greathouse — APPROVED** [review]

**Comment by sjinks** [comment]
r2078-stacks

**Comment by sjinks** [comment]
v20211214.0

**Pull request merged**
