### PR TITLE
Send alloptions alerts to vip-deploy-on-call

### PR DESCRIPTION
**Pull request by mjangda**
Better fits our internal workflows.

### CODE REVIEW

**Comment by trepmal** [comment]
This is still going to be in IRC land?

**Comment by mjangda** [comment]
@trepmal WIll go to both Slack and IRC.

**Comment by mjangda** [comment]
> 4th parameter is necessary/doing anything unless you also set the 5th/interval param: 

An interval of `0` means no expiry (https://developer.wordpress.org/reference/functions/wp_cache_add/)

**Comment by WPprodigy** [comment]
I see. The conditional will fail though: `if ( $kind && $interval ... )` = `if ( 'a8c-alloptions' && 0 ... ), which will fail.

**Comment by mjangda** [comment]
Oh, hah!

**Comment by mjangda** [comment]
r140294-deploy

**Pull request merged**
