### PR TITLE
VaultPress: Add extra debug info

### PR DESCRIPTION
**Pull request by GaryJones**
Amend the value that is already logged when pinging a site from VaultPress.com fails in a specific way (signature mismatch).

This output can be seen in the “ping test” panel in VPMC.

This is needed to debug why a live client production site isn't able to connect to VaultPress.

### CODE REVIEW

**Comment by nickdaugherty** [comment]
@GaryJones is this PR still valuable?

**Comment by GaryJones** [comment]
@nickdaugherty I no longer need it for a specific customer, but it could be useful for general logging for VaultPress issues.

**Comment by WPprodigy** [comment]
Is there are particular piece of `$_POST` that could be logged rather than the whole thing?

Otherwise, I think maybe it's okay to go ahead and close this one out.

**Comment by GaryJones** [comment]
Closing as not needed.

**Pull request closed without merging**
