### PR TITLE
Start health check only on production env

### PR DESCRIPTION
**Pull request by hanifn**
## Description

Limit the Elasticsearch health check cron job to only run on `production` sites.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.

## Steps to Test

Example:

1. Check out PR.
1. Sandbox a production site
1. `wp cron-control events list`
1. Ensure the `vip_search_healthcheck` job is scheduled

### CODE REVIEW

**Comment by nickdaugherty** [comment]
To accommodate testing on other environments, could we make it filterable instead of hardcoded to the `production` environment? Something like `apply_filters( 'enable_vip_search_healthchecks', 'production === VIP_GO_ENV )`

**Comment by hanifn** [comment]
@nickdaugherty Oh that's a good idea!

**Comment by hanifn** [comment]
> To accommodate testing on other environments, could we make it filterable instead of hardcoded to the production environment? Something like apply_filters( 'enable_vip_search_healthchecks', 'production' === VIP_GO_ENV )

@nickdaugherty Implemented in 724e3e44bc1e4199ea077bd1034cb348e38553ef

**Comment by hanifn** [comment]
r764-stacks

**Pull request merged**
