### PR TITLE
Skip indexing job from queue if index version not found

### PR DESCRIPTION
**Pull request by brandon-m-skinner**
## Description

Presently there's no handling for if the index version has been deleted before the jobs are processed from the queue.

They should not be re-indexed and they should not count towards index rate limiting.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. Apply PR.
2. Schedule a process jobs cron job for the queue that contains a list of valid IDs with a non-existent index version number.
3. Run the cron job.
4. There should be no warnings or errors from the process and the index rate limiting count shouldn't increase.

### CODE REVIEW

**Comment by pschoffer** [comment]
Would a test for this be a good idea maybe?

It seems there already is a test file for this, just needs one or two more test cases:
tests/search/includes/classes/test-class-queue.php

Buut:
```
public function test_process_jobs() {
	// TODO
}
```

**Comment by brandon-m-skinner** [comment]
Generally I'd agree. Most of my PRs are at least half tests. 

However in this case, adding tests for `process_jobs` should be a separate PR. 

The reasoning for that is:

- The change set would balloon the PR and make the actual point of the PR harder to discern. Small, focused PRs are the goal. If the tests already existed, expanding them for this change would make sense.
- It's part of an already approved change, blocking two PRs.
- The PR is minor and easily testable and based on extensively used production code meaning the risk is low.

**Review by nickdaugherty — APPROVED** [review]
Looks correct to me.

**Comment by brandon-m-skinner** [comment]
r1207-stacks

**Pull request merged**
