### PR TITLE
Add URI to New Relic

### PR DESCRIPTION
**Pull request by sboisvert**
We want to know the exact URL that was hit so we can reproduce what's happening.

### CODE REVIEW

**Comment by sboisvert** [comment]
This will also help us track down 404s

**Comment by nickdaugherty** [comment]
@sboisvert Do you envision us using this on every site, or just enabling it ad-hoc?

**Comment by sboisvert** [comment]
For all sites

**Comment by sboisvert** [comment]
Now with 100% more hooking!

**Comment by nickdaugherty** [comment]
Looks good, merging.

**Pull request merged**
