### PR TITLE
Don't call WPCOM_VIP_Cache_Manager::purge_site_cache() when saving posts under WP_IMPORTING

### LINKED ISSUE #705: Don't BAN entire site cache on clean_post_cache when WP_IMPORTING is true
Originally put in place for initial site imports - but `WP_IMPORTING` can be defined under a number of situations, such as content syndication, so we should not automatically BAN the entire site there.

https://github.com/Automattic/vip-go-mu-plugins/blob/33c65f5f72190578ba6f91315094ef3deeea8088/vip-cache-manager/vip-cache-manager.php#L271-L274

### PR DESCRIPTION
**Pull request by nickdaugherty**
WP_IMPORTING can be set under a number of conditions, such as
syndication via REST apis, and shouldn’t end up BAN-ing the entire site.

Question - what impact will this have on CLI-based imports? Lots of extra code below the removed block could end up running, which could really slow things down. Needs some thought.

Fixes #705

### CODE REVIEW

**Comment by nickdaugherty** [comment]
An alternative is to still exit early but not run the site BAN, though that's imperfect b/c can lead to stale caches.

**Comment by ethitter** [comment]
> Question - what impact will this have on CLI-based imports? Lots of extra code below the removed block could end up running, which could really slow things down. Needs some thought.

I was wondering the same thing. Perhaps we should only remove the call to `purge_site_cache()`?

**Comment by ethitter** [comment]
We might be okay with documentation, leaving it to CLI-based importers to manage caches themselves. Some clients are already actively managing their caches, so they may not notice at all.

**Comment by nickdaugherty** [comment]
r96317-deploy

**Pull request merged**
