### PR TITLE
Updating Parsely plugin loading hook

### PR DESCRIPTION
**Pull request by pauarge**
## Description

The release of Parse.ly 2.6 comes with some changes on how the code is structured. One of the main differences is that the plugin now hooks to `plugins_loaded` to initialize itself. We are currently loading `wp-parsely` on mu-plugins by using the `after_setup_theme` hook. That hook occurs after `plugins_loaded`, hence, this last one would never be triggered and the Parse.ly plugin would never be initialized.

This PR changes how the plugin is loaded by using a hook that fires earlier, `muplugins_loaded`.

### Updating Parsely plugin loading hook

Changing how Parse.ly plugin is loaded to accommodate wp-parsely 2.6.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
2. Load Parse.ly 2.6 (everything should work normally).
3. Check out master and try to load Parse.ly. Site should fatal.

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
The test needs to be updated:

```
1) Automattic\VIP\WP_Parsely_Integration\MU_Parsely_Integration_Test::test_has_maybe_load_plugin_action
```

**Comment by rinatkhaziev** [comment]
Aside from that, what's the context about changing the hook to `plugin_updated`?

**Comment by GaryJones** [comment]
Talk should be about `plugins_loaded`, not `plugins_updated` hook. See https://github.com/Parsely/wp-parsely/blob/e8d49e04377adbea8b64554c1a5a7fb02fe20d5f/wp-parsely.php#L39

**Comment by pauarge** [comment]
@GaryJones @rinatkhaziev My bad, I mistyped that. As per the link above, the hook is `plugins_loaded`.

**Comment by rinatkhaziev** [comment]
Thanks @GaryJones @pauarge

**Review by rinatkhaziev — APPROVED** [review]

**Pull request merged**
