### PR TITLE
add stripslashes_deep. move stripslashes_deep outside loops

### PR DESCRIPTION
**Pull request by rodruiz**
- Fix ERROR: 
-- stripslashes() expects parameter 1 to be string, array given. 
-- vip-go-elasticsearch.php (643)
- Solution:
-- add stripslashes_deep.
-- move stripslashes_deep outside loops

### CODE REVIEW

**Comment by mjangda** [comment]
Thanks for the PR, @rodruiz. For testing, can you please provide a way to reproduce the error?

**Comment by rodruiz** [comment]
@mjangda $_GET should be a Multi-Dimensional array

**Comment by mjangda** [comment]
Thanks @rodruiz!

**Comment by mjangda** [comment]
r94464-deploy

**Pull request merged**
