### PR TITLE
Enable logs delivery to Elasticsearch debug index for CLI containers

### PR DESCRIPTION
**Pull request by denho**
## Description
Currently, logs captured with `\Automattic\VIP\Logstash\Logger::log2logstash()` function within CLI containers don't get delivered to Elasticsearch Vip Go debug index. This happens due to CLI containers not yet running their tasks within a chroot. 
To fix that, the logs file could be forced to be placed within the `/chroot` directory. 

Thanks to @darthhexx for explaining this and providing a solution.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test
1. Check out PR.
1. Make sure the `VIP_GO_ENV` is set to `true`.
1. Make sure you have the chroot implemented and `/chroot/tmp/` directory exists. 
1. Enter WP shell `wp shell` and run `\Automattic\VIP\Logstash\Logger::log2logstash(['severity' => 'info', 'feature' => 'test', 'message' => 'hello']);`
1. Confirm the similar output added in the `/chroot/tmp/logstash.log` file:
```
{"site_id":1,"blog_id":1,"host":"","severity":"info","feature":"a8c_vip_test","message":"hello","user_id":0,"extra":"[]","timestamp":"2020-06-18 06:23:28","index":"log2logstash","file":"\/var\/www\/html\/wp-content\/mu-plugins\/logstash\/class-logger.php","line":"401"}
```

### CODE REVIEW

**Comment by brandon-m-skinner** [comment]
@darthhexx This moves all logstash files, including on web containers log into `/chroot/tmp`. Just want to confirm that works, is intended, and won't break anything.

**Comment by darthhexx** [comment]
They already are in `/chroot/tmp/php-errors` on the Web Containers, but PHP has no concept of the `/chroot` prefix on them as it is running chrooted. Only WP-CLI Containers can actually "see" the chroot directory, so this will work as expected.

**Comment by denho** [comment]
Can I merge it or should I wait for someone from the VIP team to do the merge?

**Comment by simonwheatley** [comment]
> Can I merge it or should I wait for someone from the VIP team to do the merge?

Wait, please, as there's some deployment flows we need to go through after merge.

**Comment by brandon-m-skinner** [comment]
r993-stacks

**Pull request merged**
