### PR TITLE
Cache Manager: update stats keys, track dashboard purge action

### PR DESCRIPTION
**Pull request by rinatkhaziev**
## Description

The length of the stat key is limited to `32` characters. Our keys included `vip-go-cache-manager-` prefix, which is `21` characters long, leading to stats keys truncation. 

This PR removes `go-` and `manager-` from the prefix so that keys become `vip-cache-action`, `vip-cache-url-purge-status`, and `vip-cache-url-purge-by-site`.

Additionally, introduces `vip-cache-action=dashboard-site-purge` stat.

### Improved internal stat tracking for Cache Manager

We have updated stats keys allowing us to better track usage for Cache Manager functionality.

https://github.com/Automattic/vip-go-mu-plugins/pull/1922

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] (For Automatticians) I've created a changelog draft. 

## Steps to Test

1. Check out PR on a sandbox
1. Click 'Purge Page Cache' in Dashboard
1. Verify that 'dashboard-site-purge' is tracked now

### CODE REVIEW

**Review by nickdaugherty — COMMENTED** [review]
Can we drop the `-go` also? VIP Go is just VIP these days and it'll give us an extra 3 😄

**Comment by mjangda** [comment]
Aside: we should probably trigger a warning in `send_pixel` if the length is too long.

**Comment by rinatkhaziev** [comment]
@nickdaugherty good point, I have addressed in the last commit. Now we have so many free characters I don't know what to do with it :)

@mjangda also good point! Thinking maybe a `_doing_it_wrong()` call, like `The $key length is over 32 characters limit, the key will be truncated: $truncated_key`

**Review by mjangda — APPROVED** [review]

**Review by nickdaugherty — APPROVED** [review]

**Comment by pschoffer** [comment]
stacks-r1315.

**Pull request merged**
