### PR TITLE
Bump advanced post cache

### PR DESCRIPTION
**Pull request by brandon-m-skinner**
@mjangda Reopened since the deploy blew up a site.

To add new "skip" filter for custom post types. No behaviour change here, just the new filter.

https://github.com/Automattic/advanced-post-cache/pull/18

### CODE REVIEW

**Comment by mjangda** [comment]
This needs some testing with one specific client site who ran into fatals.

**Comment by brandon-m-skinner** [comment]
I'll take a look and sort it out tomorrow if no one else does or wants to by then.

**Comment by brandon-m-skinner** [comment]
Gonna merge and deploy again.

**Comment by brandon-m-skinner** [comment]
r924-stacks

**Pull request merged**
