### PR TITLE
Shared plugins: Add defensive code to fix Warning

### PR DESCRIPTION
**Pull request by GaryJones**
## Description

Ensures that if a value stored in `wpcom_vip_active_plugins` is not an array, that the subsequent `foreach` does not run. Without it, "Invalid argument supplied for foreach" PHP Warnings are generated (currently ~3700 per day on VIP Go).

Fix could optionally also include a ` || empty( retired_plugins_option )` in the conditional as well, though the `foreach` should not through a warning for an empty array. 

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. `wp option set wpcom_vip_active_plugins notanarray`
1. Load site and check logs for "Invalid argument supplied for foreach" PHP Warnings.
1. Apply PR
1. Load site again, and check for no new PHP Warnings.

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Thanks for this @GaryJones - do you have a sense of what's causing the non-array value in the first place?

**Comment by GaryJones** [comment]
If `get_option( 'wpcom_vip_active_plugins', array() );` returns a non-array value (either from a value stored in the DB, or from a pre get option filter, then the Warning will be thrown.

**Comment by hanifn** [comment]
r771-stacks

**Comment by GaryJones** [comment]
Confirming the Warnings have stopped:

Screenshot 2020-02-12 at 12 20 28

**Comment by nickdaugherty** [comment]
Thanks @GaryJones !

**Pull request merged**
