### PR TITLE
Search: Alert if we don't have a queue count value cached OR if the queue count isn't decreasing

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description
To reduce the noise, let's add caching for the queue count and alert when the queue count isn't decreasing. 

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Review by sjinks — APPROVED** [review]

**Comment by rebeccahum** [comment]
@sjinks What are your thoughts on not alerting it there is no cached value and only caching it the first time. Then on subsequent times, only alerting if the comparison of the cached value is not less than the actual value?

**Comment by WPprodigy** [comment]
That could work, but I'd increase the cache timeout to longer than 15m then.

The only other thing to consider is an unhealthy site that has lots of memcache ejections, is possible our cache key goes away each time before it's up again to run in 5min. Seems unlikely, but worth considering.

**Comment by sjinks** [comment]
> What are your thoughts on not alerting if there is no cached value and thus, only caching it the first time

:+1:

**Comment by rebeccahum** [comment]
> The only other thing to consider is an unhealthy site that has lots of memcache ejections, is possible our cache key goes away each time before it's up again to run in 5min. Seems unlikely, but worth considering.

That did occur to me but I'm not sure what kind of failsafe we would have in place for it that wouldn't rely on memcache. I've updated the caching TTL to 45 minutes instead and I'll leave it to alert for the time being on no cached count value (just in case we do run into an unhealthy site that has constant memcache ejections — I don't think we want to be ina situation where we are expecting that alert and it doesn't alert).

**Review by WPprodigy — APPROVED** [review]

**Comment by rebeccahum** [comment]
r2115-stacks

**Pull request merged**
