### PR TITLE
Use microseconds to store the timestamp for site details sync

### PR DESCRIPTION
**Pull request by saroshaga**
## Description

In order to get more accurate audit log of when a Site Detail was updated/added, we need to store the timestamp in microseconds.

### Site Details Index Update

Use microseconds to store the timestamp for site details sync

## Checklist

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Comment by pschoffer** [comment]
Looks great. This seems kinda easy to test as it is isolated (time based stuff is harder but I guess as long as the diff from expected is within say one second it would be good). Would you like to add test for it?  Otherwise LGTM

**Comment by pschoffer** [comment]
Oh actually in Changelog please add the Changelog entry title as well. e.g. https://github.com/Automattic/vip-go-mu-plugins/pull/2693

**Comment by saroshaga** [comment]
> Would you like to add test for it? 

Yes!! In fact, this is actually where I need your help. How do I test this?

**Comment by saroshaga** [comment]
Just used a REPL to test this out instead!

**Review by rebeccahum — DISMISSED** [review]

**Review by nejclovrencic — APPROVED** [review]

**Comment by pschoffer** [comment]
@saroshaga could you please add steps to the test? Did you figure out what was the issue with float vs integer we looked at before together?

**Comment by pschoffer** [comment]
Also if we could get a unit test that would be amazing... as this is the kinda isolated function it should not be hard to do. I am happy to help with that.

**Review by pschoffer — CHANGES_REQUESTED** [review]
Sorry to be a blocker here, but would love to get more info into testing this in here for future reference.

**Comment by saroshaga** [comment]
> @saroshaga could you please add steps to the test? Did you figure out what was the issue with float vs integer we looked at before together? 

hey @pschoffer .. i could not get the var_dump to work. i used a repl to test this out. 

> Also if we could get a unit test that would be amazing... as this is the kinda isolated function it should not be hard to do. I am happy to help with that.

yeah +1 to a unit test.. will look into this

> Sorry to be a blocker here, but would love to get more info into testing this in here for future reference.

not at all!! thanks for the feedback <3

**Comment by saroshaga** [comment]
@pschoffer : I have added a unit test for this! 

However, like I mentioned in my previous comment, I was unable to test this out. I think my dev env is not starting properly

```
Compile error: require_once(): Failed opening required '/wp/wp-content/mu-plugins/cron-control/cron-control.php' (include_path='.:/usr/local/lib/php') in /wp/wp-content/mu-plugins/001-cron.php on line 167 [vip-local.vipdev.lndo.site/] []
Error: The site you have requested is not installed.
Run `wp core install` to create database tables.
Error: The site you have requested is not installed.
Run `wp core install` to create database tables.
Copying dev-env-plugin.php to mu-plugins
```

**Comment by sjinks** [comment]
@saroshaga to run unit tests locally, you can run `./bin/test.sh`. Or `./bin/test.sh /path/to/test/file.php`.

**Comment by saroshaga** [comment]
> @saroshaga to run unit tests locally, you can run `./bin/test.sh`. Or `./bin/test.sh /path/to/test/file.php`.

hey @sjinks!! I was actually trying to decode locally by adding a `var_dump` but that didn't work for me. Unit tests are working fine.

**Review by sjinks — APPROVED** [review]

**Comment by sjinks** [comment]
LGTM

**Review by pschoffer — APPROVED** [review]

**Pull request merged**
