### PR TITLE
Enforce strict username sanitization

### PR DESCRIPTION
**Pull request by brettshumaker**
Reduces the username to ASCII. All valid usernames should already be in this format. This is the equivalent of calling `sanitize_user( $username, true )` every time `sanitize_user()` is called.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Comment by GaryJones** [comment]
What problem does this solve? Are non-ASCII characters in usernames a risk? Are there any customers who are have users with accented characters, or letters outside of a-z, who this would negatively impact?

**Comment by rinatkhaziev** [comment]
Breaks core tests:

```
1) Tests_Auth::test_wp_signon_using_email_with_an_apostrophe
Failed asserting that WP_Error Object (...) is an instance of class "WP_User".

/tmp/wordpress-develop/tests/phpunit/tests/auth.php:426

2) Tests_Formatting_SanitizeUser::test_strips_encoded_ampersand_when_followed_by_semicolon
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'ATT Test;'
+'ATT Test'
```

**Review by nickdaugherty — APPROVED** [review]
LGTM, thanks for working on this!

**Comment by nickdaugherty** [comment]
Release v1.22.0

**Pull request merged**
