### PR TITLE
Update cron-control

### PR DESCRIPTION
**Pull request by brandon-m-skinner**
## Description

cron-control was updated and that update deployed, but not applied to git.

```
Index: cron-control/includes/wp-cli/class-orchestrate-sites.php
===================================================================
--- cron-control/includes/wp-cli/class-orchestrate-sites.php    (revision 945)
+++ cron-control/includes/wp-cli/class-orchestrate-sites.php    (working copy)
@@ -82,7 +82,7 @@

                // Remove stale hosts
                // If a host has missed 2 heartbeats, remove it from jobs processing
-               $heartbeats = array_filter( $heartbeats, function( $timestamp ) use ( $heartbeat_interval ) {
+               $heartbeats = array_filter( $heartbeats, function( $timestamp ) {
                        if ( time() - ( $heartbeat_interval * 2 ) > $timestamp ) {
                                return false;
                        }
```

### CODE REVIEW

**Comment by nickdaugherty** [comment]
CC @joshbetz since you worked on this.

**Comment by brandon-m-skinner** [comment]
It's already been live for over a mont.

**Comment by brandon-m-skinner** [comment]
@vincenzo You just click the Update Branch button then merge with the UI.

**Comment by joshbetz** [comment]
Looks good. Noting that the diff in the PR description is the opposite of what's being applied here.

**Comment by vincenzo** [comment]
@brandon-m-skinner Yup, just abstained because didn't know the process. I am used to leave it up to the PR owner :)

**Comment by joshbetz** [comment]
+1 for leaving to PR owner or whoever is currently working on the PR. It can be slightly annoying to have PRs diverge on GitHub if you're still working locally. There are exceptions -- if you're taking over the PR, about to merge, or otherwise coordinate with whoever is working on the PR, it's fine IMO.

**Pull request merged**
