### PR TITLE
Jetpack plan: Update VIP object for jetpack_active_plan option

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description
We're in the process of switching over Jetpack Professional (deprecated) to Complete. We need to update the default `jetpack_active_plan` option.

PR for the last time we updated: https://github.com/Automattic/vip-go-mu-plugins/pull/1431

This needs to go alongside with the below changes:
- https://github.com/Automattic/jetpack/pull/21833
- Update provisioning to use `jetpack-complete` plan

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]

**Comment by WPprodigy** [comment]
Are "active" ones going to be activated automatically for existing sites, or is this something that takes place during the initial provisioning only?

**Comment by kraftbj** [comment]
`active` is different in this context than active modules. This means features that are active within that Plan, e.g. available. 

https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/class.jetpack-plan.php#L347 uses the `active` to field to determine if a feature is supported or not.

The terminology comes from the Store codebase and basically means "this feature is available as part of the current plan".

**Review by WPprodigy — APPROVED** [review]

**Comment by rebeccahum** [comment]
@kraftbj A follow-up...this pre-option return should not negatively affect sites with a "Professional" plan in any way, correct?

**Comment by kraftbj** [comment]
Correct. Since we are effectively telling Jetpack that these sites have a "vip" plan, Professional vs Complete is immaterial with Jetpack.

**Comment by rinatkhaziev** [comment]
r2087-stacks

**Pull request merged**
