### PR TITLE
Adding a funciton for flushing wp_old_slug_redirect_cache on post_update

### PR DESCRIPTION
**Pull request by david-binda**
In case a post_name is changed and item is published, we should flush all previous wp_old_slug_redirect cache in order to prevent possible redirect loops.

### CODE REVIEW

**Comment by mjangda** [comment]
@sboisvert Did you deploy this? If so, can you please add the Deployed label and commit number?

**Comment by sboisvert** [comment]
By deployed do we mean to wpcom? If so,  yes and r286292. I'll wait for you to confirm before putting the deployed label.

**Comment by mjangda** [comment]
I mean to the VIP Go deploy repo :)

**Comment by sboisvert** [comment]
Ah then no, I can do that Monday (not sure how yet)

**Comment by mjangda** [comment]
r90510-deploy

**Pull request merged**
