### PR TITLE
WP CLI to Cron logging improvements

### PR DESCRIPTION
**Pull request by philipjohn**
Some improvements to the logging for CLI commands offloaded to cron;

* Improved the URL reported when running on multisite
* Added additional IRC logging to record the completed run

### CODE REVIEW

**Comment by mjangda** [comment]
We should probably add similar improvements to the emails?

**Comment by philipjohn** [comment]
There's already an output e-mail, so I didn't think it'd be worth doing a "finished" e-mail, and I've changed the URL on all the e-mails where it's used, I think.

**Comment by mjangda** [comment]
> I've changed the URL on all the e-mails where it's used, I think.

Sorry, I meant adding the url to emails that don't currently include them.

**Comment by mjangda** [comment]
> Sorry, I meant adding the url to emails that don't currently include them.

Added in dc3e2095

**Comment by mjangda** [comment]
r106238-deploy

**Pull request merged**
