### PR TITLE
Don't log the default value of the VIP Env var if it wasn't set

### PR DESCRIPTION
**Pull request by rinatkhaziev**
## Description

We shouldn't leak the default value into logs, merely the fact of an expected variable absent should provide enough information for debug.

### VIP Env Variables

Don't log the default value when the specified key is not set.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out the PR 
2. `wp shell`
3. `Environment::get_var( 'notexisting', 'default_value' );`
4. Verify `default_value` is not being logged.

### CODE REVIEW

**Review by WPprodigy — APPROVED** [review]
✅ . I'm not completely sure I see the need to log at all, it's similar to a `get_option( 'key', 'default value' );`, in that having a default value is a feature not necessarily a bug if it's used.

I feel like if not having a value is an error to the codebase, then the application should be checking against a default null-like value on it's own. Otherwise, defaulting to something seems perfectly reasonable in many circumstances where you don't need an environmental override.

**Review by pauarge — APPROVED** [review]
Good catch.

**Comment by rinatkhaziev** [comment]
@WPprodigy I see your point, the idea was mostly around catching potential regressions since the vars are getting propagated via other systems, it's not inconceivable that something may break there. We can always remove if it proves to be useless or too noisy.

**Comment by rinatkhaziev** [comment]
r1966-stacks

**Pull request merged**
