### PR TITLE
Sync WP.com performance tweaks

### PR DESCRIPTION
**Pull request by sboisvert**
Add performance tweaks that have been added to .com

Many of these should be enabled by default but they are not on GO they are enabled in .com inside /plugins/vip-helper-wpcom.php
Where should we add functions from that file ^^?

### CODE REVIEW

**Comment by simonwheatley** [comment]
I'd say add them in https://github.com/Automattic/vip-go-mu-plugins/blob/master/000-vip-init.php

**Comment by nickdaugherty** [comment]
I think they should go into an appropriate file in the `vip-helpers` directory - `000-vip-init.php` should really only 'bootstrap' by requiring other files.

**Comment by nickdaugherty** [comment]
All the stampedeless cache stuff here won't work b/c `require_lib` doesn't exist, and neither does the class - can we remove it? It's really easy to use it wrong and cause worse performance, so probably doesn't need to be kept.

**Comment by joshbetz** [comment]
Is there an opportunity to get any of this in core?

**Comment by joshbetz** [comment]
@sboisvert What's the status of this?

**Comment by sboisvert** [comment]
Where is the totally haven't looked at it emoji?

**Comment by joshbetz** [comment]
@sboisvert No worries. If you can push to a branch on this repo, I can help clean this up and get it deployed. Would be good to keep wp.com and Go in sync.

**Pull request closed without merging**
