### PR TITLE
vip migration cleanup: Reset user roles before trying to connect Jetpack

### PR DESCRIPTION
**Pull request by rinatkhaziev**
In order for Jetpack to be connected the machine user has to exist and be an administrator.

However, if administrator role is missing `jetpack-start connect` will fail to create the user. 

This commit addresses that by introducing `reset_user_roles` function which calls the `wp role reset --all`

### CODE REVIEW

**Comment by mjangda** [comment]
This might cause problems if we import a database with custom roles already defined?

**Comment by rinatkhaziev** [comment]
Not according to my testing, our two custom support roles are not affected when running it. But I can test again, or can add a flag to only run it for WPCOM->VIP Go migrations.

**Comment by rinatkhaziev** [comment]
Actually I think it's fine as-is. The command description explicitly states that this resets only default roles:

https://developer.wordpress.org/cli/commands/role/reset/

**Comment by mjangda** [comment]
> can add a flag to only run it for WPCOM->VIP Go migrations

I think this might be better.

**Comment by rinatkhaziev** [comment]
> 
> I think this might be better.

This will be trickier though, because it'll require changes to the import endpoint, I'm not really sure if it's warranted. Here's the source of the `wp role reset` it definitely only touches the default roles:
https://github.com/wp-cli/role-command/blob/bad54a1b02331ee6460cc6a6f967e37dd91e07a3/src/Role_Command.php

**Comment by uxcitizen** [comment]
> This might cause problems if we import a database with custom roles already defined?

In the past I frequently had to run `wp role reset --all` after imports, as roles went missing. 

Only once did it cause an issue that I am aware of and that was for #vip-client-digital-first-media - they had some custom logic on the default-named roles - 

https://github.com/wpcomvip/digital-first-media/blob/master/themes/wp-mason/inc/cli.php
Ticket: https://wordpressvip.zendesk.com/agent/tickets/82646

**Comment by mjangda** [comment]
Going to close this as we're doing it during the migration process now. Can revisit if it's still causing problems.

**Pull request closed without merging**
