### PR TITLE
Update WordPress Importer plugin to include post_type in the query for existing post

### PR DESCRIPTION
**Pull request by dhusakovic**
## Description

The post import process uses [post_exists](https://developer.wordpress.org/reference/functions/post_exists/) function to check whether each of the importing posts already exists. The query utilises the title and date parameters for this search, which will run through all the posts to try and find a match.  

In cases where we have a large number of posts this process times out and the import fails. 

Passing the **post_type** to **post_exists** function allows us to use the **type_status_date** key, which significantly drops the number of rows examined and the overall query time in certain instances, depending on how many posts of that post_type we have.

## Changelog Description

Update to WordPress Importer plugin to improve the post_exists query time during post import process.

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Review by sjinks — APPROVED** [review]

**Review by rebeccahum — CHANGES_REQUESTED** [review]
Hi @dhusakovic, thanks for the PR! Would it be possible to do the change upstream so that when we update it to the latest version, the change doesn't get overwritten? https://github.com/WordPress/wordpress-importer

**Comment by dhusakovic** [comment]
@rebeccahum  I've created an issue and suggested the change here https://github.com/WordPress/wordpress-importer/issues/162. Can we still push the update here while we wait for the upstream changes?

**Comment by rebeccahum** [comment]
@dhusakovic I'd prefer to keep it in sync with upstream to ensure it doesn't get overwritten with the way we have many moving parts in MU-plugins! However, I looked at the upstream issue and it looks like your suggestion [would be a welcome change in a PR](https://github.com/WordPress/wordpress-importer/issues/162#issuecomment-2044115739) 🙂.

**Comment by rebeccahum** [comment]
Closing b/c it's in now per #5967

**Pull request closed without merging**
