### PR TITLE
Merge VIP Support Repo

### PR DESCRIPTION
**Pull request by nickdaugherty**
## Description

Merge the [VIP Support Repo](https://github.com/Automattic/vip-support/) into this one. The maintenance overhead of having `vip-support` in a separate repo is prohibitively high for little gain, so let's combine them.

TODO:

- [x] Replace submodule with folder
- [x] Identify and fix any redundant or unused config / files
- [x] Move unit tests
- [x] Composer?

### VIP Support: Merge repository

This is a behind-the-scenes change to merge 2 repositories together for easier maintenance.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [ ] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1. Check out PR.
2. Add yourself as a support user
1. Go to WP Admin
1. Ensure you still have regular permissions and there are no errors

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
@nickdaugherty what's the status on this?

**Comment by nickdaugherty** [comment]
Mostly it's just the tests that need to be integrated with the rest of the test suite.

**Comment by sjinks** [comment]
r2278-stacks

**Comment by jesse-greathouse** [comment]
v20220210.1

**Pull request merged**
