### PR TITLE
Use filters for Search ratelimiting to allow per-site adjustments

### PR DESCRIPTION
**Pull request by brandon-m-skinner**
## Description

Not all sites need the same settings and rate limits. Some need more, some need less. Therefore, we should allow the various settings to be set via filters.

Needs validation as well as sensible upper / lower bounds for all settings to prevent issues. Also needs related unit tests.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

1. Set rate limiting thresholds for querying and indexing low.
2. Do searches and indexing operations to trigger ratelimiting.
3. Note the behaviour.
4. Apply PR.
5. Set rate limiting thresholds for querying and indexing low.
6. Do searches and indexing operations to trigger ratelimiting.
7. The behaviour should be the exact same as before the PR.

### CODE REVIEW

**Review by pschoffer — CHANGES_REQUESTED** [review]
Looks great overall, just a minor note about default values

**Review by nickdaugherty — CHANGES_REQUESTED** [review]
Overall looks good; left a note about an upper bound on the count limits.

**Review by nickdaugherty — DISMISSED** [review]
LGTM

**Comment by netsuso** [comment]
stacks-r1289

**Pull request merged**
