### PR TITLE
Add opsgenie alerts for AllOptions

### PR DESCRIPTION
**Pull request by mikeyarce**
## Description
Add OpsGenie Alerts for AllOptions! 😄

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

I tried testing this on my sandbox but there was a problem with this:
https://github.com/Automattic/vip-go-mu-plugins/blob/9c293f8325d1b4d51a15e947591e6cae4cc67a68/lib/utils/class-alerts.php#L280

The `is_int` check wasn't passing because it was a string.  

If I bypass that, I get this error (I removed the URL, IP_ADDRESS and PORT):

```
[12-Jun-2020 22:42:21 UTC] Warning: vip_safe_wp_remote_request: Blog ID 1: Requesting http://{IP_ADDRESS}:{PORT}/v1.0/alerts with method POST and a timeout of 1 failed. Result: O:8:"WP_Error":2:{s:6:"errors";a:1:{s:19:"http_request_failed";a:1:{i:0;s:78:"cURL error 7: Failed to connect to {IP_ADDRESS} port {PORT}: Connection refused";}}s:10:"error_data";a:0:{}} in /var/www/wp-content/mu-plugins/vip-helpers/vip-utils.php on line 804 [{URL}/?v=dfjnaiwufho7] [wp-content/mu-plugins/vip-helpers/vip-utils.php:804 trigger_error(), wp-content/mu-plugins/lib/utils/class-alerts.php:58 vip_safe_wp_remote_request(), wp-content/mu-plugins/lib/utils/class-alerts.php:252 Automattic\VIP\Utils\Alerts->send(), wp-content/mu-plugins/lib/utils/class-alerts.php:353 Automattic\VIP\Utils\Alerts->send_to_opsgenie(), wp-content/mu-plugins/alloptions-limit.php:137 Automattic\VIP\Utils\Alerts::opsgenie(), wp-content/mu-plugins/alloptions-limit.php:40 wpcom_vip_sanity_check_alloptions_notify(), wp-includes/class-wp-hook.php:287 wpcom_vip_sanity_check_alloptions(), wp-includes/class-wp-hook.php:311 WP_Hook->apply_filters(), wp-includes/plugin.php:478 WP_Hook->do_action(), wp-settings.php:403 do_action('plugins_loaded'), wp-config.php:11 require_once('wp-settings.php'), wp-load.php:37 require_once('wp-config.php'), wp-blog-header.php:13 require_once('wp-load.php'), index.php:17 require('wp-blog-header.php')]
[12-Jun-2020 22:42:21 UTC] Error sending alert: There was an error connecting to the alerts service
```

cc @hanifn is there something I need to do differently to test this on my sandbox?

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
I love the idea and also curious about the ALERT_SERVICE_PORT issue.

**Comment by rinatkhaziev** [comment]
Did a quick check, and indeed it's defined as a string in wp-config. so looks like this code would never run.

**Comment by mikeyarce** [comment]
Apparently there is a restriction for sending data to Gnaw from sandbox hosts, which is why this doesn't work on my sandbox.

**Comment by rinatkhaziev** [comment]
@mikeyarce 

Lint has some things to say to you:
```
/home/circleci/project/alloptions-limit.php
  71:29  error  String "P4" does not require double quotes; use single quotes instead  Squiz.Strings.DoubleQuoteUsage.NotRequired
  77:33  error  String "P3" does not require double quotes; use single quotes instead  Squiz.Strings.DoubleQuoteUsage.NotRequired
```

Could you please address it?

**Comment by brandon-m-skinner** [comment]
r1004-stacks

**Comment by GaryJones** [comment]
@mikeyarce This caused a Circle CI error for a client where the `class-alerts.php` file couldn't be loaded - see #112110-z. 

The current code added in `all-options.php` a few days ago is:

```
require_once( WP_CONTENT_DIR . '/mu-plugins/lib/utils/class-alerts.php' );
```

In the existing `000-vip-init.php` it's:

```
require_once( __DIR__ . '/lib/utils/class-alerts.php' );
```

Both `all-options.php` and `000-vip-init.php` files live in the same directory, so I would suggest updating `all-options.php` to use the same require_once that `000-vip-init.php` does.

**Pull request merged**
