### PR TITLE
Add doing_it_wrong for late loading plugins

### PR DESCRIPTION
**Pull request by mjangda**
For now, plugins loaded via code, should be loaded earlier before the theme. Preferably via `client-mu-plugins` so that any callbacks on `plugins_loaded` fire as expected.

### CODE REVIEW

**Comment by GaryJones** [comment]
> For now

Does this imply that it might change at some point in the future?

**Comment by mjangda** [comment]
> Does this imply that it might change at some point in the future?

We may consider alternate ways to load plugins via code, e.g. config files.

**Comment by brandon-m-skinner** [comment]
@mjangda Is this still PR still valid? If so I'd like to pursue its completion/deployment.

**Comment by mjangda** [comment]
Yep, still valid.

**Comment by mjangda** [comment]
PR refreshed. We'll probably want to keep an eye on warning/notice counts post-deploy.

**Comment by brandon-m-skinner** [comment]
r899-stacks

**Pull request merged**
