### PR TITLE
Update es-wp-query subtree to current 

### PR DESCRIPTION
**Pull request by jesse-greathouse**
## Description
Updates the es-wp-query subtree to its current state in `main` branch in the upstream (https://github.com/alleyinteractive/es-wp-query).

### Library Updated: es-wp-query

We upgraded es-wp-query to it's current release status as of September 6th 2022

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

### CODE REVIEW

**Comment by rebeccahum** [comment]
Hmmm, maybe we should fork `es-wp-query` to `Automattic` and sync with changes as needed because we don't need the other adapters for `es-wp-query`.

**Review by rebeccahum — CHANGES_REQUESTED** [review]
Hmmm, maybe we should fork `es-wp-query` to `Automattic` and sync with changes as needed because we don't need the other adapters for `es-wp-query`.

**Comment by rinatkhaziev** [comment]
We already fork it at https://github.com/Automattic/es-wp-query/

**Comment by jesse-greathouse** [comment]
I will make the necessary changes at the a8c fork and remake this.

**Pull request closed without merging**
