### PR TITLE
Enable new JP full sync approach for all non-prod sites

### PR DESCRIPTION
**Pull request by nickdaugherty**
## Description

Enables queue-less full sync across all non-production sites for beta testing prior to JP 8.2

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [x] This change has relevant unit tests (if applicable).
- [x] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

Example:

1. Check out PR.
1. On non-prod site, ensure the `VIP_JETPACK_FULL_SYNC_IMMEDIATELY` const is always set to `true`
1. On prod site, ensure the constant is not set
1. Define the constant in vip-config.php and ensure there are no conflicts

### CODE REVIEW

**Comment by nickdaugherty** [comment]
Need to figure out the unit tests...failing b/c constant is already defined...since we define it by default now, can no longer do the test that defines it to true/false and checks.

**Comment by mdbitz** [comment]
Don't forget to merge https://github.com/Automattic/jetpack/commit/8d9032690dbb47f2ec1b128faf42ebcfbd1c64d1 as well :)

**Comment by mdbitz** [comment]
Don't forget to merge https://github.com/Automattic/jetpack/commit/8d9032690dbb47f2ec1b128faf42ebcfbd1c64d1 as well :)

**Comment by nickdaugherty** [comment]
Yep deployed that one yesterday (directly in SVN).

**Comment by nickdaugherty** [comment]
r739-stacks

**Pull request merged**
