### PR TITLE
Brings msm-sitemap up to date

### PR DESCRIPTION
**Pull request by emrikol**
msm-sitemap is out of date, and this will bring it to commit 49b884d6a96ab386705f28a94d61745b854cfb9d

### CODE REVIEW

**Comment by joshbetz** [comment]
@emrikol What do you think about switching this to a submodule?

**Comment by emrikol** [comment]
> What do you think about switching this to a submodule?

@joshbetz That sounds like it would be a better way of keeping this up to date.  :+1:

**Comment by nickdaugherty** [comment]
@emrikol did you have a chance to look at switching this to a submodule?

**Comment by joshbetz** [comment]
Closing in favor of #318

**Pull request closed without merging**
