### PR TITLE
Allow VaultPress registration to fail gracefully

### PR DESCRIPTION
**Pull request by scarstocea**
Allow VaultPress registration to fail gracefully, but still output the error

### CODE REVIEW

**Comment by scarstocea** [comment]
This is for running the sync from CLI to start to finish – otherwise this fatal error will occur during the cleanup action on some sites, which causes the entire action to fail.

We're still debugging the VaultPress issues which cause this, but some clients require weekly syncs and their cleanup actions take a lot of time when ran manually, so we'd rather have this work for now (even as a stop gap measure).

**Comment by mjangda** [comment]
As discussed in Slack, let's go ahead and release this since it's breaking sync. It does modify the VaultPress plugin directly so we'll have to be careful not to overwrite the change with future releases (and work with the VP team to see if we can upstream this or something similar).

**Comment by mjangda** [comment]
r112157-deploy

**Comment by scarstocea** [comment]
Thanks, Mo! I'll chat with the VaultPress devs about upstreaming it.

**Pull request merged**
