### PR TITLE
Add filter to is_valid_path_for_site ACL function

### PR DESCRIPTION
**Pull request by rbcorrales**
## Description

This PR adds a filter to the `is_valid_path_for_site` function to allow overriding its behavior.
The use case for this is not necessarily to circumvent the subsite restrictions when ACL is enabled but also to allow access to other custom directories within the `wp-content/uploads` path.

This extends the functionality introduced by this PR in 2021: https://github.com/Automattic/vip-go-mu-plugins/pull/1975

### Added
- Introduced the `vip_files_acl_is_valid_path_for_site` filter to extend the `is_valid_path_for_site` function. This new filter allows overriding the VIP File System's validation process for multisite setups, which uses the `/wp-content/mu-plugins/files/acl/endpoint-check-file-acl.php` endpoint to check permissions for paths under `/wp-content/uploads`. It enables custom use cases, such as accessing directories outside the default site asset paths (but within the uploads folder) while adhering to other ACL rules. This extends the functionality introduced in PR #1975. **Warning:** Improper use of this filter could expose private data. Developers using it must ensure that the logic they implement enforces proper access control to prevent data leaks between subsites.

## Pre-review checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally or in Codespaces (or has an appropriate fallback).
- [x] This change works and has been tested on a sandbox.
- [x] This change has relevant unit tests (if applicable).
- [ ] This change uses a rollout method to ease with deployment (if applicable - especially for large scale actions that require writes).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Pre-deploy checklist

- [ ] VIP staff: Ensure any alerts added/updated conform to internal standards (see internal documentation). 

## Steps to Test

1. Clone this repo and switch to the `private-files-valid-path-filter` branch.

2. Follow the instructions for [creating a local dev environment](https://github.com/Automattic/vip-go-mu-plugins?tab=readme-ov-file#local-dev) using the repo path as mu-plugins:
```shell
> vip dev-env create --slug=test --mu-plugins $(pwd)
```

3. Start the environment:
```shell
> vip dev-env --slug=test start
```

4. Create another subsite:
```shell
> vip dev-env --slug=test exec -- wp site create --slug=subsite2 --title="Subsite 2" --email=admin@example.com
```

5. List the subsites and add both domains to your `/etc/hosts` file pointing to 127.0.0.1:
```shell
> vip dev-env --slug=test exec -- wp site list
```

6. Checking ACL for a path inside site 2 will return status `202`:
```shell
> curl http://subsite2.test.vipdev.lndo.site/wp-content/mu-plugins/files/acl/endpoint-check-file-acl.php -H 'X-Original-Uri: /wp-content/uploads/sites/2/kitty.jpg' -I
HTTP/1.1 202 Accepted
```

7. Checking ACL for a path outside site 2 will return status `400`:
```shell
> curl http://subsite2.test.vipdev.lndo.site/wp-content/mu-plugins/files/acl/endpoint-check-file-acl.php -H 'X-Original-Uri: /wp-content/uploads/custom-uploads/kitty.jpg' -I
HTTP/1.1 400 Bad Request
```

8. There should be this message in the logs:
```
NOTICE: PHP message: PHP Warning:  Blocked request for file path that is not allowed (current site ID: 2 | requested URI: /wp-content/uploads/custom-uploads/kitty.jpg) in /wp/wp-content/mu-plugins/files/acl/endpoint-check-file-acl.php on line 30
```

9. Add the following filter as a plugin in a file inside `/client-mu-plugins`:
```php
function allow_custom_uploads_path( $is_valid, $file_path ) {
	if ( str_starts_with( $file_path, 'custom-uploads/' ) ) {
		return true;
	}

	return $is_valid;
}
add_filter( 'vip_files_acl_is_valid_path_for_site', 'allow_custom_uploads_path', 10, 2 );
```

10. Repeat the previous request. It should now return `202` with no errors in the logs:
```shell
> curl http://subsite2.test.vipdev.lndo.site/wp-content/mu-plugins/files/acl/endpoint-check-file-acl.php -H 'X-Original-Uri: /wp-content/uploads/custom-uploads/kitty.jpg' -I
HTTP/1.1 202 Accepted
```

### CODE REVIEW

**Comment by rinatkhaziev** [comment]
@ramonjd left some notes in the ticket.

**Comment by rinatkhaziev** [comment]
@mjangda do you have any concerns with the proposed changes? functionally they work fine.

**Comment by mjangda** [comment]
Seems fine if there are legitimate uses we've identified for this.

Main risk is that if the code that uses the filter isn't careful, it can end up leaking private data. But that's up the developer using the filter to enforce.

**Comment by rinatkhaziev** [comment]
yeah, my thoughts exactly.

**Review by rinatkhaziev — APPROVED** [review]
Thank you for the PR @rbcorrales as well as for thorough testing! Looks good.

**Comment by rbcorrales** [comment]
Thanks, @rinatkhaziev. I updated the changelog to be more descriptive. Let me know if this looks good.

**Pull request merged**
