### PR TITLE
Update Query Monitor 3.6.5 => 3.7.1

### PR DESCRIPTION
**Pull request by johnbillion**
## Description

This updates the Query Monitor plugin from 3.6.5 to 3.7.1.

### Query Monitor updated to version 3.7.1.

Full changelog here: https://github.com/johnbillion/query-monitor/releases

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [X] This change has relevant documentation additions / updates (if applicable).
- [X] I've created a changelog description that aligns with the provided examples.

## Steps to Test

**Important:** This introduces [a new feature which exposes the SQL query logs to suitably authenticated users during REST API requests](https://querymonitor.com/blog/2021/05/debugging-wordpress-rest-api-requests/). There is no change to the privileges required to see QM's data, but this will need testing on VIP before deploying because AFAICT [VIP uses a non-standard structure for the database queries logged in the `wpdb` class](https://github.com/automattic/vip-go-mu-plugins/blob/9180eab0ff8a2792325e8a5decf59e4a25c28e56/vip-helpers/vip-query-monitor.php).

### CODE REVIEW

**Comment by pschoffer** [comment]
Thanks for the PR @johnbillion. While testing this I found the issue we have introduced, similar to the discussion in [this PR](https://github.com/johnbillion/query-monitor/pull/549).

That is that currently, we don't capture any REST calls, due to the priority change we have done [here](https://github.com/Automattic/vip-go-mu-plugins/blob/5fecaa13f2ff40ee1bdee6160b40c22f853f1a21/query-monitor.php#L157). I'll fix that first so we can verify more here.

**Comment by pschoffer** [comment]
Hmm, actually @johnbillion I might have been wrong. I am probably setting up the manual testing wrong. Could you help me with some basic scenario when the rest call should have been caught by the query monitor? Or feel free to point me to some resource to read up on.

I tried this (I do get back the response printed on the page, but nothing in the HTTP API calls in the query monitor):
```
function tmp_request() {
	$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
	$request->set_param( 'per_page', 2 );
	$response = rest_do_request( $request );
	var_dump(['REST TEst', $response]);
}

add_action( 'wp_body_open', 'tmp_request' );
```

**Comment by johnbillion** [comment]
You'll want to test this with a client-side request instead of a server-side request because you need to perform an enveloped request for the full output. Details are in the links above.

The easiest way to do this client side is to set up an application password in your WordPress user profile, then use an HTTP client such as Insomnia or Postman with the username and password in BasicAuth.

**Comment by pschoffer** [comment]
Oh right now I get it.  Thanks for the patience.

I tested using something like:
```
function tmp_request() {
	print '<script>
		let username = "username";
		let password = "password";

		let headers = new Headers();

		headers.set("Authorization", "Basic " + btoa(username + ":" + password));
		fetch("http://vip-local.vipdev.lndo.site//wp-json/wp/v2/posts/1?_envelope", {headers: headers}).then(console.log);
	</script>
	';
}

add_action( 'wp_footer', 'tmp_request' );
```

However I didn't manage to get the BaseAuth to work as expected...so I commented the part of the code that verifies ` self::user_can_view()` in both REST and REST_Envelope dispatchers. After which I did get the `qm` object in the response and the new headers back.

The `gm` headers lack some expected values due to us having our custom Query collector. Most notable `results` aren't collected. But we still get the query sql, stack and the time. 

Everything else I tested works as expected.

**Comment by pschoffer** [comment]
I tested it some more on sandbox + ran our regular test pipeline. Looks all good. Deploying to staging next.

**Comment by johnbillion** [comment]
Do we need to trigger a new deployment in order for an updated `mu-plugins` directory to be deployed to our staging and prod sites?

**Comment by pauarge** [comment]
@johnbillion It should be deployed to staging and prod now.

**Pull request merged**
