### PR TITLE
Add homeUrl field to Site Details Sync

### PR DESCRIPTION
**Pull request by saroshaga**
## Description

We want to sync the `home_url` option with our Site Details database. 

### Changelog Entry Update

Add homeUrl field to Site Details Sync.

It uses the `get_home_url()` [function](https://developer.wordpress.org/reference/functions/get_home_url/) to fetch the data and the Site Details Index to sync

## Checklist

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).
- [x] I've created a changelog description that aligns with the provided examples.

## Steps to Test

1) Use any site
2) Check if the option returns the correct value

### CODE REVIEW

**Review by rebeccahum — APPROVED** [review]
@saroshaga Are we good to deploy this right away or do we need to coordinate on your end?

**Comment by saroshaga** [comment]
> @saroshaga Are we good to deploy this right away or do we need to coordinate on your end?

thanks for the review @rebeccahum !! This PR is good to be deployed!

**Comment by rebeccahum** [comment]
@saroshaga I've deployed it to staging now. It should be deployed to production on Tuesday.

**Comment by rebeccahum** [comment]
r2073-stacks

**Comment by saroshaga** [comment]
thank you @rebeccahum

**Comment by saroshaga** [comment]
@rebeccahum : do i look at the public changelog to confirm if my changes have been deployed?

**Comment by rebeccahum** [comment]
@saroshaga Wait for the "Deployed to Staging" label to be removed and replaced with "Deployed to Production" on this PR.

**Comment by sjinks** [comment]
v20211214.0

**Pull request merged**
